/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// AddLibraryItemRequest
    /// </summary>
    [DataContract]
    public partial class AddLibraryItemRequest :  IEquatable<AddLibraryItemRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddLibraryItemRequest" /> class.
        /// </summary>
        /// <param name="cjson">Cjson to be added to library.</param>
        /// <param name="contentType">flow, campaign, cjson, email, transactional_email or upsell.</param>
        /// <param name="description">description of library item.</param>
        /// <param name="storefrontOid">StoreFront oid where content originates necessary for tracking down relative assets.</param>
        /// <param name="title">title of library item, usually the name of the flow or campaign, or description of cjson.</param>
        /// <param name="uuid">UUID of communication flow or campaign, null if this item is neither.</param>
        public AddLibraryItemRequest(string cjson = default(string), string contentType = default(string), string description = default(string), int? storefrontOid = default(int?), string title = default(string), string uuid = default(string))
        {
            this.Cjson = cjson;
            this.ContentType = contentType;
            this.Description = description;
            this.StorefrontOid = storefrontOid;
            this.Title = title;
            this.Uuid = uuid;
        }
        
        /// <summary>
        /// Cjson to be added to library
        /// </summary>
        /// <value>Cjson to be added to library</value>
        [DataMember(Name="cjson", EmitDefaultValue=false)]
        public string Cjson { get; set; }

        /// <summary>
        /// flow, campaign, cjson, email, transactional_email or upsell
        /// </summary>
        /// <value>flow, campaign, cjson, email, transactional_email or upsell</value>
        [DataMember(Name="content_type", EmitDefaultValue=false)]
        public string ContentType { get; set; }

        /// <summary>
        /// description of library item
        /// </summary>
        /// <value>description of library item</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// StoreFront oid where content originates necessary for tracking down relative assets
        /// </summary>
        /// <value>StoreFront oid where content originates necessary for tracking down relative assets</value>
        [DataMember(Name="storefront_oid", EmitDefaultValue=false)]
        public int? StorefrontOid { get; set; }

        /// <summary>
        /// title of library item, usually the name of the flow or campaign, or description of cjson
        /// </summary>
        /// <value>title of library item, usually the name of the flow or campaign, or description of cjson</value>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// UUID of communication flow or campaign, null if this item is neither
        /// </summary>
        /// <value>UUID of communication flow or campaign, null if this item is neither</value>
        [DataMember(Name="uuid", EmitDefaultValue=false)]
        public string Uuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AddLibraryItemRequest {\n");
            sb.Append("  Cjson: ").Append(Cjson).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  StorefrontOid: ").Append(StorefrontOid).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddLibraryItemRequest);
        }

        /// <summary>
        /// Returns true if AddLibraryItemRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddLibraryItemRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddLibraryItemRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Cjson == input.Cjson ||
                    (this.Cjson != null &&
                    this.Cjson.Equals(input.Cjson))
                ) && 
                (
                    this.ContentType == input.ContentType ||
                    (this.ContentType != null &&
                    this.ContentType.Equals(input.ContentType))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.StorefrontOid == input.StorefrontOid ||
                    (this.StorefrontOid != null &&
                    this.StorefrontOid.Equals(input.StorefrontOid))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Uuid == input.Uuid ||
                    (this.Uuid != null &&
                    this.Uuid.Equals(input.Uuid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cjson != null)
                    hashCode = hashCode * 59 + this.Cjson.GetHashCode();
                if (this.ContentType != null)
                    hashCode = hashCode * 59 + this.ContentType.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.StorefrontOid != null)
                    hashCode = hashCode * 59 + this.StorefrontOid.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Uuid != null)
                    hashCode = hashCode * 59 + this.Uuid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
