/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// AffiliateMarketingStrategy
    /// </summary>
    [DataContract]
    public partial class AffiliateMarketingStrategy :  IEquatable<AffiliateMarketingStrategy>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AffiliateMarketingStrategy" /> class.
        /// </summary>
        /// <param name="marketingStrategy">Description of their marketing strategy.</param>
        /// <param name="usingAdNetwork">True if they are using an ad network.</param>
        /// <param name="usingAdware">True if they are using ad software.</param>
        /// <param name="usingBlog">True if they are using their blog.</param>
        /// <param name="usingOther">True if they are using some ohter marketing technique.</param>
        /// <param name="usingPerAcquisition">True if they are using a per acquisition model.</param>
        /// <param name="usingPpc">True if they are using pay per click ads.</param>
        /// <param name="usingSeo">True if they are using search engine optimization techniques.</param>
        /// <param name="usingWebsite">True if they are driving traffic from their website.</param>
        /// <param name="websiteName">Name of the affiliates website.</param>
        /// <param name="websiteUrl">URL of the affiliates website.</param>
        public AffiliateMarketingStrategy(string marketingStrategy = default(string), bool usingAdNetwork = default(bool), bool usingAdware = default(bool), bool usingBlog = default(bool), string usingOther = default(string), bool usingPerAcquisition = default(bool), bool usingPpc = default(bool), bool usingSeo = default(bool), bool usingWebsite = default(bool), string websiteName = default(string), string websiteUrl = default(string))
        {
            this.MarketingStrategy = marketingStrategy;
            this.UsingAdNetwork = usingAdNetwork;
            this.UsingAdware = usingAdware;
            this.UsingBlog = usingBlog;
            this.UsingOther = usingOther;
            this.UsingPerAcquisition = usingPerAcquisition;
            this.UsingPpc = usingPpc;
            this.UsingSeo = usingSeo;
            this.UsingWebsite = usingWebsite;
            this.WebsiteName = websiteName;
            this.WebsiteUrl = websiteUrl;
        }

        /// <summary>
        /// Description of their marketing strategy
        /// </summary>
        /// <value>Description of their marketing strategy</value>
        [DataMember(Name="marketing_strategy", EmitDefaultValue=false)]
        public string MarketingStrategy { get; set; }

        /// <summary>
        /// True if they are using an ad network
        /// </summary>
        /// <value>True if they are using an ad network</value>
        [DataMember(Name="using_ad_network", EmitDefaultValue=false)]
        public bool UsingAdNetwork { get; set; }

        /// <summary>
        /// True if they are using ad software
        /// </summary>
        /// <value>True if they are using ad software</value>
        [DataMember(Name="using_adware", EmitDefaultValue=false)]
        public bool UsingAdware { get; set; }

        /// <summary>
        /// True if they are using their blog
        /// </summary>
        /// <value>True if they are using their blog</value>
        [DataMember(Name="using_blog", EmitDefaultValue=false)]
        public bool UsingBlog { get; set; }

        /// <summary>
        /// True if they are using some ohter marketing technique
        /// </summary>
        /// <value>True if they are using some ohter marketing technique</value>
        [DataMember(Name="using_other", EmitDefaultValue=false)]
        public string UsingOther { get; set; }

        /// <summary>
        /// True if they are using a per acquisition model
        /// </summary>
        /// <value>True if they are using a per acquisition model</value>
        [DataMember(Name="using_per_acquisition", EmitDefaultValue=false)]
        public bool UsingPerAcquisition { get; set; }

        /// <summary>
        /// True if they are using pay per click ads
        /// </summary>
        /// <value>True if they are using pay per click ads</value>
        [DataMember(Name="using_ppc", EmitDefaultValue=false)]
        public bool UsingPpc { get; set; }

        /// <summary>
        /// True if they are using search engine optimization techniques
        /// </summary>
        /// <value>True if they are using search engine optimization techniques</value>
        [DataMember(Name="using_seo", EmitDefaultValue=false)]
        public bool UsingSeo { get; set; }

        /// <summary>
        /// True if they are driving traffic from their website
        /// </summary>
        /// <value>True if they are driving traffic from their website</value>
        [DataMember(Name="using_website", EmitDefaultValue=false)]
        public bool UsingWebsite { get; set; }

        /// <summary>
        /// Name of the affiliates website
        /// </summary>
        /// <value>Name of the affiliates website</value>
        [DataMember(Name="website_name", EmitDefaultValue=false)]
        public string WebsiteName { get; set; }

        /// <summary>
        /// URL of the affiliates website
        /// </summary>
        /// <value>URL of the affiliates website</value>
        [DataMember(Name="website_url", EmitDefaultValue=false)]
        public string WebsiteUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AffiliateMarketingStrategy {\n");
            sb.Append("  MarketingStrategy: ").Append(MarketingStrategy).Append("\n");
            sb.Append("  UsingAdNetwork: ").Append(UsingAdNetwork).Append("\n");
            sb.Append("  UsingAdware: ").Append(UsingAdware).Append("\n");
            sb.Append("  UsingBlog: ").Append(UsingBlog).Append("\n");
            sb.Append("  UsingOther: ").Append(UsingOther).Append("\n");
            sb.Append("  UsingPerAcquisition: ").Append(UsingPerAcquisition).Append("\n");
            sb.Append("  UsingPpc: ").Append(UsingPpc).Append("\n");
            sb.Append("  UsingSeo: ").Append(UsingSeo).Append("\n");
            sb.Append("  UsingWebsite: ").Append(UsingWebsite).Append("\n");
            sb.Append("  WebsiteName: ").Append(WebsiteName).Append("\n");
            sb.Append("  WebsiteUrl: ").Append(WebsiteUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AffiliateMarketingStrategy);
        }

        /// <summary>
        /// Returns true if AffiliateMarketingStrategy instances are equal
        /// </summary>
        /// <param name="input">Instance of AffiliateMarketingStrategy to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AffiliateMarketingStrategy input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.MarketingStrategy == input.MarketingStrategy ||
                    (this.MarketingStrategy != null &&
                    this.MarketingStrategy.Equals(input.MarketingStrategy))
                ) && 
                (
                    this.UsingAdNetwork == input.UsingAdNetwork ||
                    (this.UsingAdNetwork != null &&
                    this.UsingAdNetwork.Equals(input.UsingAdNetwork))
                ) && 
                (
                    this.UsingAdware == input.UsingAdware ||
                    (this.UsingAdware != null &&
                    this.UsingAdware.Equals(input.UsingAdware))
                ) && 
                (
                    this.UsingBlog == input.UsingBlog ||
                    (this.UsingBlog != null &&
                    this.UsingBlog.Equals(input.UsingBlog))
                ) && 
                (
                    this.UsingOther == input.UsingOther ||
                    (this.UsingOther != null &&
                    this.UsingOther.Equals(input.UsingOther))
                ) && 
                (
                    this.UsingPerAcquisition == input.UsingPerAcquisition ||
                    (this.UsingPerAcquisition != null &&
                    this.UsingPerAcquisition.Equals(input.UsingPerAcquisition))
                ) && 
                (
                    this.UsingPpc == input.UsingPpc ||
                    (this.UsingPpc != null &&
                    this.UsingPpc.Equals(input.UsingPpc))
                ) && 
                (
                    this.UsingSeo == input.UsingSeo ||
                    (this.UsingSeo != null &&
                    this.UsingSeo.Equals(input.UsingSeo))
                ) && 
                (
                    this.UsingWebsite == input.UsingWebsite ||
                    (this.UsingWebsite != null &&
                    this.UsingWebsite.Equals(input.UsingWebsite))
                ) && 
                (
                    this.WebsiteName == input.WebsiteName ||
                    (this.WebsiteName != null &&
                    this.WebsiteName.Equals(input.WebsiteName))
                ) && 
                (
                    this.WebsiteUrl == input.WebsiteUrl ||
                    (this.WebsiteUrl != null &&
                    this.WebsiteUrl.Equals(input.WebsiteUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MarketingStrategy != null)
                    hashCode = hashCode * 59 + this.MarketingStrategy.GetHashCode();
                if (this.UsingAdNetwork != null)
                    hashCode = hashCode * 59 + this.UsingAdNetwork.GetHashCode();
                if (this.UsingAdware != null)
                    hashCode = hashCode * 59 + this.UsingAdware.GetHashCode();
                if (this.UsingBlog != null)
                    hashCode = hashCode * 59 + this.UsingBlog.GetHashCode();
                if (this.UsingOther != null)
                    hashCode = hashCode * 59 + this.UsingOther.GetHashCode();
                if (this.UsingPerAcquisition != null)
                    hashCode = hashCode * 59 + this.UsingPerAcquisition.GetHashCode();
                if (this.UsingPpc != null)
                    hashCode = hashCode * 59 + this.UsingPpc.GetHashCode();
                if (this.UsingSeo != null)
                    hashCode = hashCode * 59 + this.UsingSeo.GetHashCode();
                if (this.UsingWebsite != null)
                    hashCode = hashCode * 59 + this.UsingWebsite.GetHashCode();
                if (this.WebsiteName != null)
                    hashCode = hashCode * 59 + this.WebsiteName.GetHashCode();
                if (this.WebsiteUrl != null)
                    hashCode = hashCode * 59 + this.WebsiteUrl.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
