/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// CartCheckout
    /// </summary>
    [DataContract]
    public partial class CartCheckout :  IEquatable<CartCheckout>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartCheckout" /> class.
        /// </summary>
        /// <param name="Comments">Comments from the customer.  Rarely used on the single page checkout..</param>
        /// <param name="CustomField1">Custom field 1.</param>
        /// <param name="CustomField2">Custom field 2.</param>
        /// <param name="CustomField3">Custom field 3.</param>
        /// <param name="CustomField4">Custom field 4.</param>
        /// <param name="CustomField5">Custom field 5.</param>
        /// <param name="CustomField6">Custom field 6.</param>
        /// <param name="CustomField7">Custom field 7.</param>
        /// <param name="IpAddress">IP Address.</param>
        /// <param name="ScreenBrandingThemeCode">Screen branding theme code.</param>
        public CartCheckout(string Comments = null, string CustomField1 = null, string CustomField2 = null, string CustomField3 = null, string CustomField4 = null, string CustomField5 = null, string CustomField6 = null, string CustomField7 = null, string IpAddress = null, string ScreenBrandingThemeCode = null)
        {
            this.Comments = Comments;
            this.CustomField1 = CustomField1;
            this.CustomField2 = CustomField2;
            this.CustomField3 = CustomField3;
            this.CustomField4 = CustomField4;
            this.CustomField5 = CustomField5;
            this.CustomField6 = CustomField6;
            this.CustomField7 = CustomField7;
            this.IpAddress = IpAddress;
            this.ScreenBrandingThemeCode = ScreenBrandingThemeCode;
        }
        
        /// <summary>
        /// Comments from the customer.  Rarely used on the single page checkout.
        /// </summary>
        /// <value>Comments from the customer.  Rarely used on the single page checkout.</value>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public string Comments { get; set; }
        /// <summary>
        /// Custom field 1
        /// </summary>
        /// <value>Custom field 1</value>
        [DataMember(Name="custom_field1", EmitDefaultValue=false)]
        public string CustomField1 { get; set; }
        /// <summary>
        /// Custom field 2
        /// </summary>
        /// <value>Custom field 2</value>
        [DataMember(Name="custom_field2", EmitDefaultValue=false)]
        public string CustomField2 { get; set; }
        /// <summary>
        /// Custom field 3
        /// </summary>
        /// <value>Custom field 3</value>
        [DataMember(Name="custom_field3", EmitDefaultValue=false)]
        public string CustomField3 { get; set; }
        /// <summary>
        /// Custom field 4
        /// </summary>
        /// <value>Custom field 4</value>
        [DataMember(Name="custom_field4", EmitDefaultValue=false)]
        public string CustomField4 { get; set; }
        /// <summary>
        /// Custom field 5
        /// </summary>
        /// <value>Custom field 5</value>
        [DataMember(Name="custom_field5", EmitDefaultValue=false)]
        public string CustomField5 { get; set; }
        /// <summary>
        /// Custom field 6
        /// </summary>
        /// <value>Custom field 6</value>
        [DataMember(Name="custom_field6", EmitDefaultValue=false)]
        public string CustomField6 { get; set; }
        /// <summary>
        /// Custom field 7
        /// </summary>
        /// <value>Custom field 7</value>
        [DataMember(Name="custom_field7", EmitDefaultValue=false)]
        public string CustomField7 { get; set; }
        /// <summary>
        /// IP Address
        /// </summary>
        /// <value>IP Address</value>
        [DataMember(Name="ip_address", EmitDefaultValue=false)]
        public string IpAddress { get; set; }
        /// <summary>
        /// Screen branding theme code
        /// </summary>
        /// <value>Screen branding theme code</value>
        [DataMember(Name="screen_branding_theme_code", EmitDefaultValue=false)]
        public string ScreenBrandingThemeCode { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CartCheckout {\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  CustomField1: ").Append(CustomField1).Append("\n");
            sb.Append("  CustomField2: ").Append(CustomField2).Append("\n");
            sb.Append("  CustomField3: ").Append(CustomField3).Append("\n");
            sb.Append("  CustomField4: ").Append(CustomField4).Append("\n");
            sb.Append("  CustomField5: ").Append(CustomField5).Append("\n");
            sb.Append("  CustomField6: ").Append(CustomField6).Append("\n");
            sb.Append("  CustomField7: ").Append(CustomField7).Append("\n");
            sb.Append("  IpAddress: ").Append(IpAddress).Append("\n");
            sb.Append("  ScreenBrandingThemeCode: ").Append(ScreenBrandingThemeCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CartCheckout);
        }

        /// <summary>
        /// Returns true if CartCheckout instances are equal
        /// </summary>
        /// <param name="other">Instance of CartCheckout to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartCheckout other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Comments == other.Comments ||
                    this.Comments != null &&
                    this.Comments.Equals(other.Comments)
                ) && 
                (
                    this.CustomField1 == other.CustomField1 ||
                    this.CustomField1 != null &&
                    this.CustomField1.Equals(other.CustomField1)
                ) && 
                (
                    this.CustomField2 == other.CustomField2 ||
                    this.CustomField2 != null &&
                    this.CustomField2.Equals(other.CustomField2)
                ) && 
                (
                    this.CustomField3 == other.CustomField3 ||
                    this.CustomField3 != null &&
                    this.CustomField3.Equals(other.CustomField3)
                ) && 
                (
                    this.CustomField4 == other.CustomField4 ||
                    this.CustomField4 != null &&
                    this.CustomField4.Equals(other.CustomField4)
                ) && 
                (
                    this.CustomField5 == other.CustomField5 ||
                    this.CustomField5 != null &&
                    this.CustomField5.Equals(other.CustomField5)
                ) && 
                (
                    this.CustomField6 == other.CustomField6 ||
                    this.CustomField6 != null &&
                    this.CustomField6.Equals(other.CustomField6)
                ) && 
                (
                    this.CustomField7 == other.CustomField7 ||
                    this.CustomField7 != null &&
                    this.CustomField7.Equals(other.CustomField7)
                ) && 
                (
                    this.IpAddress == other.IpAddress ||
                    this.IpAddress != null &&
                    this.IpAddress.Equals(other.IpAddress)
                ) && 
                (
                    this.ScreenBrandingThemeCode == other.ScreenBrandingThemeCode ||
                    this.ScreenBrandingThemeCode != null &&
                    this.ScreenBrandingThemeCode.Equals(other.ScreenBrandingThemeCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Comments != null)
                    hash = hash * 59 + this.Comments.GetHashCode();
                if (this.CustomField1 != null)
                    hash = hash * 59 + this.CustomField1.GetHashCode();
                if (this.CustomField2 != null)
                    hash = hash * 59 + this.CustomField2.GetHashCode();
                if (this.CustomField3 != null)
                    hash = hash * 59 + this.CustomField3.GetHashCode();
                if (this.CustomField4 != null)
                    hash = hash * 59 + this.CustomField4.GetHashCode();
                if (this.CustomField5 != null)
                    hash = hash * 59 + this.CustomField5.GetHashCode();
                if (this.CustomField6 != null)
                    hash = hash * 59 + this.CustomField6.GetHashCode();
                if (this.CustomField7 != null)
                    hash = hash * 59 + this.CustomField7.GetHashCode();
                if (this.IpAddress != null)
                    hash = hash * 59 + this.IpAddress.GetHashCode();
                if (this.ScreenBrandingThemeCode != null)
                    hash = hash * 59 + this.ScreenBrandingThemeCode.GetHashCode();
                return hash;
            }
        }
    }

}
