/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ConversationPbxDefaultTimezoneUpdateRequest
    /// </summary>
    [DataContract]
    public partial class ConversationPbxDefaultTimezoneUpdateRequest :  IEquatable<ConversationPbxDefaultTimezoneUpdateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConversationPbxDefaultTimezoneUpdateRequest" /> class.
        /// </summary>
        /// <param name="defaultTimezone">Merchant default timezone (IANA name, e.g. &#39;America/New_York&#39;).</param>
        public ConversationPbxDefaultTimezoneUpdateRequest(string defaultTimezone = default(string))
        {
            this.DefaultTimezone = defaultTimezone;
        }

        /// <summary>
        /// Merchant default timezone (IANA name, e.g. &#39;America/New_York&#39;)
        /// </summary>
        /// <value>Merchant default timezone (IANA name, e.g. &#39;America/New_York&#39;)</value>
        [DataMember(Name="default_timezone", EmitDefaultValue=false)]
        public string DefaultTimezone { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConversationPbxDefaultTimezoneUpdateRequest {\n");
            sb.Append("  DefaultTimezone: ").Append(DefaultTimezone).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConversationPbxDefaultTimezoneUpdateRequest);
        }

        /// <summary>
        /// Returns true if ConversationPbxDefaultTimezoneUpdateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ConversationPbxDefaultTimezoneUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConversationPbxDefaultTimezoneUpdateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DefaultTimezone == input.DefaultTimezone ||
                    (this.DefaultTimezone != null &&
                    this.DefaultTimezone.Equals(input.DefaultTimezone))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DefaultTimezone != null)
                    hashCode = hashCode * 59 + this.DefaultTimezone.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DefaultTimezone (string) maxLength
            if(this.DefaultTimezone != null && this.DefaultTimezone.Length > 60)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DefaultTimezone, length must be less than 60.", new [] { "DefaultTimezone" });
            }


            yield break;
        }
    }

}
