/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ConversationJoinRequest
    /// </summary>
    [DataContract]
    public partial class ConversationJoinRequest :  IEquatable<ConversationJoinRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConversationJoinRequest" /> class.
        /// </summary>
        /// <param name="participantLanguageIsoCode">participantLanguageIsoCode.</param>
        public ConversationJoinRequest(string participantLanguageIsoCode = default(string))
        {
            this.ParticipantLanguageIsoCode = participantLanguageIsoCode;
        }

        /// <summary>
        /// Gets or Sets ParticipantLanguageIsoCode
        /// </summary>
        [DataMember(Name="participant_language_iso_code", EmitDefaultValue=false)]
        public string ParticipantLanguageIsoCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConversationJoinRequest {\n");
            sb.Append("  ParticipantLanguageIsoCode: ").Append(ParticipantLanguageIsoCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConversationJoinRequest);
        }

        /// <summary>
        /// Returns true if ConversationJoinRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ConversationJoinRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConversationJoinRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ParticipantLanguageIsoCode == input.ParticipantLanguageIsoCode ||
                    (this.ParticipantLanguageIsoCode != null &&
                    this.ParticipantLanguageIsoCode.Equals(input.ParticipantLanguageIsoCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ParticipantLanguageIsoCode != null)
                    hashCode = hashCode * 59 + this.ParticipantLanguageIsoCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
