/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ConversationWebsocketMessage
    /// </summary>
    [DataContract]
    public partial class ConversationWebsocketMessage :  IEquatable<ConversationWebsocketMessage>, IValidatableObject
    {
        /// <summary>
        /// Type of event
        /// </summary>
        /// <value>Type of event</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventTypeEnum
        {
            
            /// <summary>
            /// Enum Queueposition for value: queue position
            /// </summary>
            [EnumMember(Value = "queue position")]
            Queueposition = 1,
            
            /// <summary>
            /// Enum Webchatstartconversation for value: webchat start conversation
            /// </summary>
            [EnumMember(Value = "webchat start conversation")]
            Webchatstartconversation = 2,
            
            /// <summary>
            /// Enum Conversationclosed for value: conversation closed
            /// </summary>
            [EnumMember(Value = "conversation closed")]
            Conversationclosed = 3,
            
            /// <summary>
            /// Enum Newconversation for value: new conversation
            /// </summary>
            [EnumMember(Value = "new conversation")]
            Newconversation = 4,
            
            /// <summary>
            /// Enum Newmessage for value: new message
            /// </summary>
            [EnumMember(Value = "new message")]
            Newmessage = 5,
            
            /// <summary>
            /// Enum Updatedmessage for value: updated message
            /// </summary>
            [EnumMember(Value = "updated message")]
            Updatedmessage = 6,
            
            /// <summary>
            /// Enum Queuestatusupdate for value: queue status update
            /// </summary>
            [EnumMember(Value = "queue status update")]
            Queuestatusupdate = 7,
            
            /// <summary>
            /// Enum Rrweb for value: rrweb
            /// </summary>
            [EnumMember(Value = "rrweb")]
            Rrweb = 8,
            
            /// <summary>
            /// Enum Participantupdate for value: participant update
            /// </summary>
            [EnumMember(Value = "participant update")]
            Participantupdate = 9,
            
            /// <summary>
            /// Enum Readmessage for value: read message
            /// </summary>
            [EnumMember(Value = "read message")]
            Readmessage = 10,
            
            /// <summary>
            /// Enum Typing for value: typing
            /// </summary>
            [EnumMember(Value = "typing")]
            Typing = 11,
            
            /// <summary>
            /// Enum Addcoupon for value: add coupon
            /// </summary>
            [EnumMember(Value = "add coupon")]
            Addcoupon = 12,
            
            /// <summary>
            /// Enum Additem for value: add item
            /// </summary>
            [EnumMember(Value = "add item")]
            Additem = 13
        }

        /// <summary>
        /// Type of event
        /// </summary>
        /// <value>Type of event</value>
        [DataMember(Name="event_type", EmitDefaultValue=false)]
        public EventTypeEnum? EventType { get; set; }
        /// <summary>
        /// Type of message
        /// </summary>
        /// <value>Type of message</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum Message for value: message
            /// </summary>
            [EnumMember(Value = "message")]
            Message = 1,
            
            /// <summary>
            /// Enum Event for value: event
            /// </summary>
            [EnumMember(Value = "event")]
            Event = 2,
            
            /// <summary>
            /// Enum Ping for value: ping
            /// </summary>
            [EnumMember(Value = "ping")]
            Ping = 3,
            
            /// <summary>
            /// Enum Checkqueueposition for value: check queue position
            /// </summary>
            [EnumMember(Value = "check queue position")]
            Checkqueueposition = 4
        }

        /// <summary>
        /// Type of message
        /// </summary>
        /// <value>Type of message</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ConversationWebsocketMessage" /> class.
        /// </summary>
        /// <param name="conversationUuid">Conversation UUID if the websocket message is tied to a specific conversation.</param>
        /// <param name="eventAddCoupon">eventAddCoupon.</param>
        /// <param name="eventAddItem">eventAddItem.</param>
        /// <param name="eventConversationClosed">eventConversationClosed.</param>
        /// <param name="eventNewConversation">eventNewConversation.</param>
        /// <param name="eventNewMessage">eventNewMessage.</param>
        /// <param name="eventParticipantUpdate">eventParticipantUpdate.</param>
        /// <param name="eventQueuePosition">eventQueuePosition.</param>
        /// <param name="eventQueueStatusUpdate">eventQueueStatusUpdate.</param>
        /// <param name="eventReadMessage">eventReadMessage.</param>
        /// <param name="eventRrweb">eventRrweb.</param>
        /// <param name="eventType">Type of event.</param>
        /// <param name="eventTyping">eventTyping.</param>
        /// <param name="eventUpdatedMessage">eventUpdatedMessage.</param>
        /// <param name="message">message.</param>
        /// <param name="type">Type of message.</param>
        public ConversationWebsocketMessage(string conversationUuid = default(string), ConversationEventAddCoupon eventAddCoupon = default(ConversationEventAddCoupon), ConversationEventAddItem eventAddItem = default(ConversationEventAddItem), ConversationSummary eventConversationClosed = default(ConversationSummary), ConversationSummary eventNewConversation = default(ConversationSummary), ConversationSummary eventNewMessage = default(ConversationSummary), ConversationSummary eventParticipantUpdate = default(ConversationSummary), ConversationEventQueuePosition eventQueuePosition = default(ConversationEventQueuePosition), ConversationWebchatQueueStatus eventQueueStatusUpdate = default(ConversationWebchatQueueStatus), ConversationEventReadMessage eventReadMessage = default(ConversationEventReadMessage), ConversationEventRRWeb eventRrweb = default(ConversationEventRRWeb), EventTypeEnum? eventType = default(EventTypeEnum?), ConversationEventTyping eventTyping = default(ConversationEventTyping), ConversationMessage eventUpdatedMessage = default(ConversationMessage), ConversationMessage message = default(ConversationMessage), TypeEnum? type = default(TypeEnum?))
        {
            this.ConversationUuid = conversationUuid;
            this.EventAddCoupon = eventAddCoupon;
            this.EventAddItem = eventAddItem;
            this.EventConversationClosed = eventConversationClosed;
            this.EventNewConversation = eventNewConversation;
            this.EventNewMessage = eventNewMessage;
            this.EventParticipantUpdate = eventParticipantUpdate;
            this.EventQueuePosition = eventQueuePosition;
            this.EventQueueStatusUpdate = eventQueueStatusUpdate;
            this.EventReadMessage = eventReadMessage;
            this.EventRrweb = eventRrweb;
            this.EventType = eventType;
            this.EventTyping = eventTyping;
            this.EventUpdatedMessage = eventUpdatedMessage;
            this.Message = message;
            this.Type = type;
        }
        
        /// <summary>
        /// Conversation UUID if the websocket message is tied to a specific conversation
        /// </summary>
        /// <value>Conversation UUID if the websocket message is tied to a specific conversation</value>
        [DataMember(Name="conversation_uuid", EmitDefaultValue=false)]
        public string ConversationUuid { get; set; }

        /// <summary>
        /// Gets or Sets EventAddCoupon
        /// </summary>
        [DataMember(Name="event_add_coupon", EmitDefaultValue=false)]
        public ConversationEventAddCoupon EventAddCoupon { get; set; }

        /// <summary>
        /// Gets or Sets EventAddItem
        /// </summary>
        [DataMember(Name="event_add_item", EmitDefaultValue=false)]
        public ConversationEventAddItem EventAddItem { get; set; }

        /// <summary>
        /// Gets or Sets EventConversationClosed
        /// </summary>
        [DataMember(Name="event_conversation_closed", EmitDefaultValue=false)]
        public ConversationSummary EventConversationClosed { get; set; }

        /// <summary>
        /// Gets or Sets EventNewConversation
        /// </summary>
        [DataMember(Name="event_new_conversation", EmitDefaultValue=false)]
        public ConversationSummary EventNewConversation { get; set; }

        /// <summary>
        /// Gets or Sets EventNewMessage
        /// </summary>
        [DataMember(Name="event_new_message", EmitDefaultValue=false)]
        public ConversationSummary EventNewMessage { get; set; }

        /// <summary>
        /// Gets or Sets EventParticipantUpdate
        /// </summary>
        [DataMember(Name="event_participant_update", EmitDefaultValue=false)]
        public ConversationSummary EventParticipantUpdate { get; set; }

        /// <summary>
        /// Gets or Sets EventQueuePosition
        /// </summary>
        [DataMember(Name="event_queue_position", EmitDefaultValue=false)]
        public ConversationEventQueuePosition EventQueuePosition { get; set; }

        /// <summary>
        /// Gets or Sets EventQueueStatusUpdate
        /// </summary>
        [DataMember(Name="event_queue_status_update", EmitDefaultValue=false)]
        public ConversationWebchatQueueStatus EventQueueStatusUpdate { get; set; }

        /// <summary>
        /// Gets or Sets EventReadMessage
        /// </summary>
        [DataMember(Name="event_read_message", EmitDefaultValue=false)]
        public ConversationEventReadMessage EventReadMessage { get; set; }

        /// <summary>
        /// Gets or Sets EventRrweb
        /// </summary>
        [DataMember(Name="event_rrweb", EmitDefaultValue=false)]
        public ConversationEventRRWeb EventRrweb { get; set; }


        /// <summary>
        /// Gets or Sets EventTyping
        /// </summary>
        [DataMember(Name="event_typing", EmitDefaultValue=false)]
        public ConversationEventTyping EventTyping { get; set; }

        /// <summary>
        /// Gets or Sets EventUpdatedMessage
        /// </summary>
        [DataMember(Name="event_updated_message", EmitDefaultValue=false)]
        public ConversationMessage EventUpdatedMessage { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="message", EmitDefaultValue=false)]
        public ConversationMessage Message { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConversationWebsocketMessage {\n");
            sb.Append("  ConversationUuid: ").Append(ConversationUuid).Append("\n");
            sb.Append("  EventAddCoupon: ").Append(EventAddCoupon).Append("\n");
            sb.Append("  EventAddItem: ").Append(EventAddItem).Append("\n");
            sb.Append("  EventConversationClosed: ").Append(EventConversationClosed).Append("\n");
            sb.Append("  EventNewConversation: ").Append(EventNewConversation).Append("\n");
            sb.Append("  EventNewMessage: ").Append(EventNewMessage).Append("\n");
            sb.Append("  EventParticipantUpdate: ").Append(EventParticipantUpdate).Append("\n");
            sb.Append("  EventQueuePosition: ").Append(EventQueuePosition).Append("\n");
            sb.Append("  EventQueueStatusUpdate: ").Append(EventQueueStatusUpdate).Append("\n");
            sb.Append("  EventReadMessage: ").Append(EventReadMessage).Append("\n");
            sb.Append("  EventRrweb: ").Append(EventRrweb).Append("\n");
            sb.Append("  EventType: ").Append(EventType).Append("\n");
            sb.Append("  EventTyping: ").Append(EventTyping).Append("\n");
            sb.Append("  EventUpdatedMessage: ").Append(EventUpdatedMessage).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConversationWebsocketMessage);
        }

        /// <summary>
        /// Returns true if ConversationWebsocketMessage instances are equal
        /// </summary>
        /// <param name="input">Instance of ConversationWebsocketMessage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConversationWebsocketMessage input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConversationUuid == input.ConversationUuid ||
                    (this.ConversationUuid != null &&
                    this.ConversationUuid.Equals(input.ConversationUuid))
                ) && 
                (
                    this.EventAddCoupon == input.EventAddCoupon ||
                    (this.EventAddCoupon != null &&
                    this.EventAddCoupon.Equals(input.EventAddCoupon))
                ) && 
                (
                    this.EventAddItem == input.EventAddItem ||
                    (this.EventAddItem != null &&
                    this.EventAddItem.Equals(input.EventAddItem))
                ) && 
                (
                    this.EventConversationClosed == input.EventConversationClosed ||
                    (this.EventConversationClosed != null &&
                    this.EventConversationClosed.Equals(input.EventConversationClosed))
                ) && 
                (
                    this.EventNewConversation == input.EventNewConversation ||
                    (this.EventNewConversation != null &&
                    this.EventNewConversation.Equals(input.EventNewConversation))
                ) && 
                (
                    this.EventNewMessage == input.EventNewMessage ||
                    (this.EventNewMessage != null &&
                    this.EventNewMessage.Equals(input.EventNewMessage))
                ) && 
                (
                    this.EventParticipantUpdate == input.EventParticipantUpdate ||
                    (this.EventParticipantUpdate != null &&
                    this.EventParticipantUpdate.Equals(input.EventParticipantUpdate))
                ) && 
                (
                    this.EventQueuePosition == input.EventQueuePosition ||
                    (this.EventQueuePosition != null &&
                    this.EventQueuePosition.Equals(input.EventQueuePosition))
                ) && 
                (
                    this.EventQueueStatusUpdate == input.EventQueueStatusUpdate ||
                    (this.EventQueueStatusUpdate != null &&
                    this.EventQueueStatusUpdate.Equals(input.EventQueueStatusUpdate))
                ) && 
                (
                    this.EventReadMessage == input.EventReadMessage ||
                    (this.EventReadMessage != null &&
                    this.EventReadMessage.Equals(input.EventReadMessage))
                ) && 
                (
                    this.EventRrweb == input.EventRrweb ||
                    (this.EventRrweb != null &&
                    this.EventRrweb.Equals(input.EventRrweb))
                ) && 
                (
                    this.EventType == input.EventType ||
                    (this.EventType != null &&
                    this.EventType.Equals(input.EventType))
                ) && 
                (
                    this.EventTyping == input.EventTyping ||
                    (this.EventTyping != null &&
                    this.EventTyping.Equals(input.EventTyping))
                ) && 
                (
                    this.EventUpdatedMessage == input.EventUpdatedMessage ||
                    (this.EventUpdatedMessage != null &&
                    this.EventUpdatedMessage.Equals(input.EventUpdatedMessage))
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConversationUuid != null)
                    hashCode = hashCode * 59 + this.ConversationUuid.GetHashCode();
                if (this.EventAddCoupon != null)
                    hashCode = hashCode * 59 + this.EventAddCoupon.GetHashCode();
                if (this.EventAddItem != null)
                    hashCode = hashCode * 59 + this.EventAddItem.GetHashCode();
                if (this.EventConversationClosed != null)
                    hashCode = hashCode * 59 + this.EventConversationClosed.GetHashCode();
                if (this.EventNewConversation != null)
                    hashCode = hashCode * 59 + this.EventNewConversation.GetHashCode();
                if (this.EventNewMessage != null)
                    hashCode = hashCode * 59 + this.EventNewMessage.GetHashCode();
                if (this.EventParticipantUpdate != null)
                    hashCode = hashCode * 59 + this.EventParticipantUpdate.GetHashCode();
                if (this.EventQueuePosition != null)
                    hashCode = hashCode * 59 + this.EventQueuePosition.GetHashCode();
                if (this.EventQueueStatusUpdate != null)
                    hashCode = hashCode * 59 + this.EventQueueStatusUpdate.GetHashCode();
                if (this.EventReadMessage != null)
                    hashCode = hashCode * 59 + this.EventReadMessage.GetHashCode();
                if (this.EventRrweb != null)
                    hashCode = hashCode * 59 + this.EventRrweb.GetHashCode();
                if (this.EventType != null)
                    hashCode = hashCode * 59 + this.EventType.GetHashCode();
                if (this.EventTyping != null)
                    hashCode = hashCode * 59 + this.EventTyping.GetHashCode();
                if (this.EventUpdatedMessage != null)
                    hashCode = hashCode * 59 + this.EventUpdatedMessage.GetHashCode();
                if (this.Message != null)
                    hashCode = hashCode * 59 + this.Message.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
