/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// FraudRuleSearchRequest
    /// </summary>
    [DataContract]
    public partial class FraudRuleSearchRequest :  IEquatable<FraudRuleSearchRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines FailureAction
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FailureActionEnum
        {
            /// <summary>
            /// Enum FlagForReview for value: Flag For Review
            /// </summary>
            [EnumMember(Value = "Flag For Review")]
            FlagForReview = 1,

            /// <summary>
            /// Enum ProcessPaymentandModify for value: Process Payment and Modify
            /// </summary>
            [EnumMember(Value = "Process Payment and Modify")]
            ProcessPaymentandModify = 2,

            /// <summary>
            /// Enum ProcessPaymentandReview for value: Process Payment and Review
            /// </summary>
            [EnumMember(Value = "Process Payment and Review")]
            ProcessPaymentandReview = 3,

            /// <summary>
            /// Enum DeclineTransaction for value: Decline Transaction
            /// </summary>
            [EnumMember(Value = "Decline Transaction")]
            DeclineTransaction = 4,

            /// <summary>
            /// Enum Exempt for value: Exempt
            /// </summary>
            [EnumMember(Value = "Exempt")]
            Exempt = 5

        }

        /// <summary>
        /// Gets or Sets FailureAction
        /// </summary>
        [DataMember(Name="failure_action", EmitDefaultValue=false)]
        public FailureActionEnum? FailureAction { get; set; }
        /// <summary>
        /// Rule group to filter by.
        /// </summary>
        /// <value>Rule group to filter by.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RuleGroupEnum
        {
            /// <summary>
            /// Enum ExemptRules for value: exemptRules
            /// </summary>
            [EnumMember(Value = "exemptRules")]
            ExemptRules = 1,

            /// <summary>
            /// Enum CreditCardRules for value: creditCardRules
            /// </summary>
            [EnumMember(Value = "creditCardRules")]
            CreditCardRules = 2,

            /// <summary>
            /// Enum IpRules for value: ipRules
            /// </summary>
            [EnumMember(Value = "ipRules")]
            IpRules = 3,

            /// <summary>
            /// Enum AddressRules for value: addressRules
            /// </summary>
            [EnumMember(Value = "addressRules")]
            AddressRules = 4,

            /// <summary>
            /// Enum AffiliateRules for value: affiliateRules
            /// </summary>
            [EnumMember(Value = "affiliateRules")]
            AffiliateRules = 5,

            /// <summary>
            /// Enum ItemRules for value: itemRules
            /// </summary>
            [EnumMember(Value = "itemRules")]
            ItemRules = 6,

            /// <summary>
            /// Enum OrderRules for value: orderRules
            /// </summary>
            [EnumMember(Value = "orderRules")]
            OrderRules = 7,

            /// <summary>
            /// Enum BrowserRules for value: browserRules
            /// </summary>
            [EnumMember(Value = "browserRules")]
            BrowserRules = 8

        }

        /// <summary>
        /// Rule group to filter by.
        /// </summary>
        /// <value>Rule group to filter by.</value>
        [DataMember(Name="rule_group", EmitDefaultValue=false)]
        public RuleGroupEnum? RuleGroup { get; set; }
        /// <summary>
        /// Rule type to filter by.
        /// </summary>
        /// <value>Rule type to filter by.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RuleTypeEnum
        {
            /// <summary>
            /// Enum Exemptapofpo for value: exempt apo fpo
            /// </summary>
            [EnumMember(Value = "exempt apo fpo")]
            Exemptapofpo = 1,

            /// <summary>
            /// Enum Exemptip for value: exempt ip
            /// </summary>
            [EnumMember(Value = "exempt ip")]
            Exemptip = 2,

            /// <summary>
            /// Enum Exemptloggedincustomerwithpricingtier for value: exempt logged in customer with pricing tier
            /// </summary>
            [EnumMember(Value = "exempt logged in customer with pricing tier")]
            Exemptloggedincustomerwithpricingtier = 3,

            /// <summary>
            /// Enum Creditcardsingletransactionexceeds for value: credit card single transaction exceeds
            /// </summary>
            [EnumMember(Value = "credit card single transaction exceeds")]
            Creditcardsingletransactionexceeds = 4,

            /// <summary>
            /// Enum Creditcarddailytransactionamountexceeds for value: credit card daily transaction amount exceeds
            /// </summary>
            [EnumMember(Value = "credit card daily transaction amount exceeds")]
            Creditcarddailytransactionamountexceeds = 5,

            /// <summary>
            /// Enum Creditcarddailytransactioncountexceeds for value: credit card daily transaction count exceeds
            /// </summary>
            [EnumMember(Value = "credit card daily transaction count exceeds")]
            Creditcarddailytransactioncountexceeds = 6,

            /// <summary>
            /// Enum Creditcardweeklytransactionamountexceeds for value: credit card weekly transaction amount exceeds
            /// </summary>
            [EnumMember(Value = "credit card weekly transaction amount exceeds")]
            Creditcardweeklytransactionamountexceeds = 7,

            /// <summary>
            /// Enum Creditcardweeklytransactioncountexceeds for value: credit card weekly transaction count exceeds
            /// </summary>
            [EnumMember(Value = "credit card weekly transaction count exceeds")]
            Creditcardweeklytransactioncountexceeds = 8,

            /// <summary>
            /// Enum Creditcardchangenumber for value: credit card change number
            /// </summary>
            [EnumMember(Value = "credit card change number")]
            Creditcardchangenumber = 9,

            /// <summary>
            /// Enum Creditcardblockbin for value: credit card block bin
            /// </summary>
            [EnumMember(Value = "credit card block bin")]
            Creditcardblockbin = 10,

            /// <summary>
            /// Enum Creditcardblockprepaid for value: credit card block prepaid
            /// </summary>
            [EnumMember(Value = "credit card block prepaid")]
            Creditcardblockprepaid = 11,

            /// <summary>
            /// Enum Amazonspecialinstructions for value: amazon special instructions
            /// </summary>
            [EnumMember(Value = "amazon special instructions")]
            Amazonspecialinstructions = 12,

            /// <summary>
            /// Enum Paypalspecialinstructions for value: paypal special instructions
            /// </summary>
            [EnumMember(Value = "paypal special instructions")]
            Paypalspecialinstructions = 13,

            /// <summary>
            /// Enum Rewardcouponemailmismatch for value: reward coupon email mismatch
            /// </summary>
            [EnumMember(Value = "reward coupon email mismatch")]
            Rewardcouponemailmismatch = 14,

            /// <summary>
            /// Enum Gatewayresponse for value: gateway response
            /// </summary>
            [EnumMember(Value = "gateway response")]
            Gatewayresponse = 15,

            /// <summary>
            /// Enum Ipdailytransactionamountexceeds for value: ip daily transaction amount exceeds
            /// </summary>
            [EnumMember(Value = "ip daily transaction amount exceeds")]
            Ipdailytransactionamountexceeds = 16,

            /// <summary>
            /// Enum Ipdailytransactioncountexceeds for value: ip daily transaction count exceeds
            /// </summary>
            [EnumMember(Value = "ip daily transaction count exceeds")]
            Ipdailytransactioncountexceeds = 17,

            /// <summary>
            /// Enum Ipweeklytransactionamountexceeds for value: ip weekly transaction amount exceeds
            /// </summary>
            [EnumMember(Value = "ip weekly transaction amount exceeds")]
            Ipweeklytransactionamountexceeds = 18,

            /// <summary>
            /// Enum Ipweeklytransactioncountexceeds for value: ip weekly transaction count exceeds
            /// </summary>
            [EnumMember(Value = "ip weekly transaction count exceeds")]
            Ipweeklytransactioncountexceeds = 19,

            /// <summary>
            /// Enum Ipmatches for value: ip matches
            /// </summary>
            [EnumMember(Value = "ip matches")]
            Ipmatches = 20,

            /// <summary>
            /// Enum Ipcountrymismatch for value: ip country mismatch
            /// </summary>
            [EnumMember(Value = "ip country mismatch")]
            Ipcountrymismatch = 21,

            /// <summary>
            /// Enum Addressfraudscoreexceeds for value: address fraud score exceeds
            /// </summary>
            [EnumMember(Value = "address fraud score exceeds")]
            Addressfraudscoreexceeds = 22,

            /// <summary>
            /// Enum Addressfraudscoreexceedsexemptapofpo for value: address fraud score exceeds exempt apo fpo
            /// </summary>
            [EnumMember(Value = "address fraud score exceeds exempt apo fpo")]
            Addressfraudscoreexceedsexemptapofpo = 23,

            /// <summary>
            /// Enum Addressstreetandzipavs for value: address street and zip avs
            /// </summary>
            [EnumMember(Value = "address street and zip avs")]
            Addressstreetandzipavs = 24,

            /// <summary>
            /// Enum Addressbillingdoesntmatchshipping for value: address billing doesnt match shipping
            /// </summary>
            [EnumMember(Value = "address billing doesnt match shipping")]
            Addressbillingdoesntmatchshipping = 25,

            /// <summary>
            /// Enum Billingcountrydoesntmatchshipping for value: billing country doesnt match shipping
            /// </summary>
            [EnumMember(Value = "billing country doesnt match shipping")]
            Billingcountrydoesntmatchshipping = 26,

            /// <summary>
            /// Enum Addressinternational for value: address international
            /// </summary>
            [EnumMember(Value = "address international")]
            Addressinternational = 27,

            /// <summary>
            /// Enum Addressmatchexceptzip for value: address match except zip
            /// </summary>
            [EnumMember(Value = "address match except zip")]
            Addressmatchexceptzip = 28,

            /// <summary>
            /// Enum Addressemail for value: address email
            /// </summary>
            [EnumMember(Value = "address email")]
            Addressemail = 29,

            /// <summary>
            /// Enum Addressnotincountry for value: address not in country
            /// </summary>
            [EnumMember(Value = "address not in country")]
            Addressnotincountry = 30,

            /// <summary>
            /// Enum Wholesalecustomernotloggedin for value: wholesale customer not logged in
            /// </summary>
            [EnumMember(Value = "wholesale customer not logged in")]
            Wholesalecustomernotloggedin = 31,

            /// <summary>
            /// Enum Affiliatematches for value: affiliate matches
            /// </summary>
            [EnumMember(Value = "affiliate matches")]
            Affiliatematches = 32,

            /// <summary>
            /// Enum Affiliatedailycountexceeds for value: affiliate daily count exceeds
            /// </summary>
            [EnumMember(Value = "affiliate daily count exceeds")]
            Affiliatedailycountexceeds = 33,

            /// <summary>
            /// Enum Affiliateweeklycountexceeds for value: affiliate weekly count exceeds
            /// </summary>
            [EnumMember(Value = "affiliate weekly count exceeds")]
            Affiliateweeklycountexceeds = 34,

            /// <summary>
            /// Enum Affiliatedailydeclinepercentageexceeds for value: affiliate daily decline percentage exceeds
            /// </summary>
            [EnumMember(Value = "affiliate daily decline percentage exceeds")]
            Affiliatedailydeclinepercentageexceeds = 35,

            /// <summary>
            /// Enum Affiliateweeklydeclinepercentageexceeds for value: affiliate weekly decline percentage exceeds
            /// </summary>
            [EnumMember(Value = "affiliate weekly decline percentage exceeds")]
            Affiliateweeklydeclinepercentageexceeds = 36,

            /// <summary>
            /// Enum Affiliatedailywithsameip for value: affiliate daily with same ip
            /// </summary>
            [EnumMember(Value = "affiliate daily with same ip")]
            Affiliatedailywithsameip = 37,

            /// <summary>
            /// Enum Affiliateweeklywithsameip for value: affiliate weekly with same ip
            /// </summary>
            [EnumMember(Value = "affiliate weekly with same ip")]
            Affiliateweeklywithsameip = 38,

            /// <summary>
            /// Enum Itemmatches for value: item matches
            /// </summary>
            [EnumMember(Value = "item matches")]
            Itemmatches = 39,

            /// <summary>
            /// Enum Itemquantityexceeds for value: item quantity exceeds
            /// </summary>
            [EnumMember(Value = "item quantity exceeds")]
            Itemquantityexceeds = 40,

            /// <summary>
            /// Enum Orderpreviousreturn for value: order previous return
            /// </summary>
            [EnumMember(Value = "order previous return")]
            Orderpreviousreturn = 41,

            /// <summary>
            /// Enum Orderpurchasedwithinlasthours for value: order purchased within last hours
            /// </summary>
            [EnumMember(Value = "order purchased within last hours")]
            Orderpurchasedwithinlasthours = 42,

            /// <summary>
            /// Enum Orderusedcouponmeantforsharing for value: order used coupon meant for sharing
            /// </summary>
            [EnumMember(Value = "order used coupon meant for sharing")]
            Orderusedcouponmeantforsharing = 43,

            /// <summary>
            /// Enum Browseroslinux for value: browser os linux
            /// </summary>
            [EnumMember(Value = "browser os linux")]
            Browseroslinux = 44

        }

        /// <summary>
        /// Rule type to filter by.
        /// </summary>
        /// <value>Rule type to filter by.</value>
        [DataMember(Name="rule_type", EmitDefaultValue=false)]
        public RuleTypeEnum? RuleType { get; set; }
        /// <summary>
        /// Defines UserAction
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum UserActionEnum
        {
            /// <summary>
            /// Enum Attempted for value: Attempted
            /// </summary>
            [EnumMember(Value = "Attempted")]
            Attempted = 1,

            /// <summary>
            /// Enum Approved for value: Approved
            /// </summary>
            [EnumMember(Value = "Approved")]
            Approved = 2

        }

        /// <summary>
        /// Gets or Sets UserAction
        /// </summary>
        [DataMember(Name="user_action", EmitDefaultValue=false)]
        public UserActionEnum? UserAction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FraudRuleSearchRequest" /> class.
        /// </summary>
        /// <param name="affiliateOidOrEmail">Affiliate oid (integer) or affiliate email. Email is resolved to oid before searching..</param>
        /// <param name="amountThresholdBegin">Lower bound on amount/score/percentage thresholds (rules backed by the same numeric column)..</param>
        /// <param name="amountThresholdEnd">amountThresholdEnd.</param>
        /// <param name="autoNote">Wildcard search on the rule&#39;s auto_note. Use &#39;*&#39; for wildcards..</param>
        /// <param name="countThresholdBegin">Lower bound on count thresholds (rules backed by the same integer count column)..</param>
        /// <param name="countThresholdEnd">countThresholdEnd.</param>
        /// <param name="createdBy">createdBy.</param>
        /// <param name="createdDateBegin">Rule creation date begin (MM/dd/yyyy).</param>
        /// <param name="createdDateEnd">Rule creation date end (MM/dd/yyyy).</param>
        /// <param name="creditCardPartial">Partial credit card number for matching &#39;credit card matches&#39; rules. Use &#39;*&#39; wildcards..</param>
        /// <param name="declineMessage">Wildcard search on the rule&#39;s decline_message. Use &#39;*&#39; for wildcards..</param>
        /// <param name="failureAction">failureAction.</param>
        /// <param name="gatewayCode">gatewayCode.</param>
        /// <param name="merchantItemId">merchantItemId.</param>
        /// <param name="modifierValue">Wildcard search on the rule&#39;s secondary modifier (eg &#39;address&#39;/&#39;subnet&#39;, gateway codes, avs match types)..</param>
        /// <param name="modifyCustomField1">modifyCustomField1.</param>
        /// <param name="modifyCustomField2">modifyCustomField2.</param>
        /// <param name="modifyCustomField3">modifyCustomField3.</param>
        /// <param name="modifyCustomField4">modifyCustomField4.</param>
        /// <param name="modifyCustomField5">modifyCustomField5.</param>
        /// <param name="modifyCustomField6">modifyCustomField6.</param>
        /// <param name="modifyCustomField7">modifyCustomField7.</param>
        /// <param name="modifySkipAffiliate">modifySkipAffiliate.</param>
        /// <param name="modifySkipAffiliateNetworkPixel">modifySkipAffiliateNetworkPixel.</param>
        /// <param name="ruleGroup">Rule group to filter by..</param>
        /// <param name="ruleType">Rule type to filter by..</param>
        /// <param name="searchLinkedAccounts">Include rules from accounts linked to this merchant. Defaults to false..</param>
        /// <param name="storefrontHostname">storefrontHostname.</param>
        /// <param name="textValue">Wildcard search on the rule&#39;s text parameter (email / ip / bin / country / item id / avs codes - the backend disambiguates by rule_type)..</param>
        /// <param name="themeCode">themeCode.</param>
        /// <param name="userAction">userAction.</param>
        public FraudRuleSearchRequest(string affiliateOidOrEmail = default(string), decimal amountThresholdBegin = default(decimal), decimal amountThresholdEnd = default(decimal), string autoNote = default(string), int countThresholdBegin = default(int), int countThresholdEnd = default(int), string createdBy = default(string), string createdDateBegin = default(string), string createdDateEnd = default(string), string creditCardPartial = default(string), string declineMessage = default(string), FailureActionEnum? failureAction = default(FailureActionEnum?), string gatewayCode = default(string), string merchantItemId = default(string), string modifierValue = default(string), string modifyCustomField1 = default(string), string modifyCustomField2 = default(string), string modifyCustomField3 = default(string), string modifyCustomField4 = default(string), string modifyCustomField5 = default(string), string modifyCustomField6 = default(string), string modifyCustomField7 = default(string), bool modifySkipAffiliate = default(bool), bool modifySkipAffiliateNetworkPixel = default(bool), RuleGroupEnum? ruleGroup = default(RuleGroupEnum?), RuleTypeEnum? ruleType = default(RuleTypeEnum?), bool searchLinkedAccounts = default(bool), string storefrontHostname = default(string), string textValue = default(string), string themeCode = default(string), UserActionEnum? userAction = default(UserActionEnum?))
        {
            this.AffiliateOidOrEmail = affiliateOidOrEmail;
            this.AmountThresholdBegin = amountThresholdBegin;
            this.AmountThresholdEnd = amountThresholdEnd;
            this.AutoNote = autoNote;
            this.CountThresholdBegin = countThresholdBegin;
            this.CountThresholdEnd = countThresholdEnd;
            this.CreatedBy = createdBy;
            this.CreatedDateBegin = createdDateBegin;
            this.CreatedDateEnd = createdDateEnd;
            this.CreditCardPartial = creditCardPartial;
            this.DeclineMessage = declineMessage;
            this.FailureAction = failureAction;
            this.GatewayCode = gatewayCode;
            this.MerchantItemId = merchantItemId;
            this.ModifierValue = modifierValue;
            this.ModifyCustomField1 = modifyCustomField1;
            this.ModifyCustomField2 = modifyCustomField2;
            this.ModifyCustomField3 = modifyCustomField3;
            this.ModifyCustomField4 = modifyCustomField4;
            this.ModifyCustomField5 = modifyCustomField5;
            this.ModifyCustomField6 = modifyCustomField6;
            this.ModifyCustomField7 = modifyCustomField7;
            this.ModifySkipAffiliate = modifySkipAffiliate;
            this.ModifySkipAffiliateNetworkPixel = modifySkipAffiliateNetworkPixel;
            this.RuleGroup = ruleGroup;
            this.RuleType = ruleType;
            this.SearchLinkedAccounts = searchLinkedAccounts;
            this.StorefrontHostname = storefrontHostname;
            this.TextValue = textValue;
            this.ThemeCode = themeCode;
            this.UserAction = userAction;
        }

        /// <summary>
        /// Affiliate oid (integer) or affiliate email. Email is resolved to oid before searching.
        /// </summary>
        /// <value>Affiliate oid (integer) or affiliate email. Email is resolved to oid before searching.</value>
        [DataMember(Name="affiliate_oid_or_email", EmitDefaultValue=false)]
        public string AffiliateOidOrEmail { get; set; }

        /// <summary>
        /// Lower bound on amount/score/percentage thresholds (rules backed by the same numeric column).
        /// </summary>
        /// <value>Lower bound on amount/score/percentage thresholds (rules backed by the same numeric column).</value>
        [DataMember(Name="amount_threshold_begin", EmitDefaultValue=false)]
        public decimal AmountThresholdBegin { get; set; }

        /// <summary>
        /// Gets or Sets AmountThresholdEnd
        /// </summary>
        [DataMember(Name="amount_threshold_end", EmitDefaultValue=false)]
        public decimal AmountThresholdEnd { get; set; }

        /// <summary>
        /// Wildcard search on the rule&#39;s auto_note. Use &#39;*&#39; for wildcards.
        /// </summary>
        /// <value>Wildcard search on the rule&#39;s auto_note. Use &#39;*&#39; for wildcards.</value>
        [DataMember(Name="auto_note", EmitDefaultValue=false)]
        public string AutoNote { get; set; }

        /// <summary>
        /// Lower bound on count thresholds (rules backed by the same integer count column).
        /// </summary>
        /// <value>Lower bound on count thresholds (rules backed by the same integer count column).</value>
        [DataMember(Name="count_threshold_begin", EmitDefaultValue=false)]
        public int CountThresholdBegin { get; set; }

        /// <summary>
        /// Gets or Sets CountThresholdEnd
        /// </summary>
        [DataMember(Name="count_threshold_end", EmitDefaultValue=false)]
        public int CountThresholdEnd { get; set; }

        /// <summary>
        /// Gets or Sets CreatedBy
        /// </summary>
        [DataMember(Name="created_by", EmitDefaultValue=false)]
        public string CreatedBy { get; set; }

        /// <summary>
        /// Rule creation date begin (MM/dd/yyyy)
        /// </summary>
        /// <value>Rule creation date begin (MM/dd/yyyy)</value>
        [DataMember(Name="created_date_begin", EmitDefaultValue=false)]
        public string CreatedDateBegin { get; set; }

        /// <summary>
        /// Rule creation date end (MM/dd/yyyy)
        /// </summary>
        /// <value>Rule creation date end (MM/dd/yyyy)</value>
        [DataMember(Name="created_date_end", EmitDefaultValue=false)]
        public string CreatedDateEnd { get; set; }

        /// <summary>
        /// Partial credit card number for matching &#39;credit card matches&#39; rules. Use &#39;*&#39; wildcards.
        /// </summary>
        /// <value>Partial credit card number for matching &#39;credit card matches&#39; rules. Use &#39;*&#39; wildcards.</value>
        [DataMember(Name="credit_card_partial", EmitDefaultValue=false)]
        public string CreditCardPartial { get; set; }

        /// <summary>
        /// Wildcard search on the rule&#39;s decline_message. Use &#39;*&#39; for wildcards.
        /// </summary>
        /// <value>Wildcard search on the rule&#39;s decline_message. Use &#39;*&#39; for wildcards.</value>
        [DataMember(Name="decline_message", EmitDefaultValue=false)]
        public string DeclineMessage { get; set; }


        /// <summary>
        /// Gets or Sets GatewayCode
        /// </summary>
        [DataMember(Name="gateway_code", EmitDefaultValue=false)]
        public string GatewayCode { get; set; }

        /// <summary>
        /// Gets or Sets MerchantItemId
        /// </summary>
        [DataMember(Name="merchant_item_id", EmitDefaultValue=false)]
        public string MerchantItemId { get; set; }

        /// <summary>
        /// Wildcard search on the rule&#39;s secondary modifier (eg &#39;address&#39;/&#39;subnet&#39;, gateway codes, avs match types).
        /// </summary>
        /// <value>Wildcard search on the rule&#39;s secondary modifier (eg &#39;address&#39;/&#39;subnet&#39;, gateway codes, avs match types).</value>
        [DataMember(Name="modifier_value", EmitDefaultValue=false)]
        public string ModifierValue { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField1
        /// </summary>
        [DataMember(Name="modify_custom_field1", EmitDefaultValue=false)]
        public string ModifyCustomField1 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField2
        /// </summary>
        [DataMember(Name="modify_custom_field2", EmitDefaultValue=false)]
        public string ModifyCustomField2 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField3
        /// </summary>
        [DataMember(Name="modify_custom_field3", EmitDefaultValue=false)]
        public string ModifyCustomField3 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField4
        /// </summary>
        [DataMember(Name="modify_custom_field4", EmitDefaultValue=false)]
        public string ModifyCustomField4 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField5
        /// </summary>
        [DataMember(Name="modify_custom_field5", EmitDefaultValue=false)]
        public string ModifyCustomField5 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField6
        /// </summary>
        [DataMember(Name="modify_custom_field6", EmitDefaultValue=false)]
        public string ModifyCustomField6 { get; set; }

        /// <summary>
        /// Gets or Sets ModifyCustomField7
        /// </summary>
        [DataMember(Name="modify_custom_field7", EmitDefaultValue=false)]
        public string ModifyCustomField7 { get; set; }

        /// <summary>
        /// Gets or Sets ModifySkipAffiliate
        /// </summary>
        [DataMember(Name="modify_skip_affiliate", EmitDefaultValue=false)]
        public bool ModifySkipAffiliate { get; set; }

        /// <summary>
        /// Gets or Sets ModifySkipAffiliateNetworkPixel
        /// </summary>
        [DataMember(Name="modify_skip_affiliate_network_pixel", EmitDefaultValue=false)]
        public bool ModifySkipAffiliateNetworkPixel { get; set; }



        /// <summary>
        /// Include rules from accounts linked to this merchant. Defaults to false.
        /// </summary>
        /// <value>Include rules from accounts linked to this merchant. Defaults to false.</value>
        [DataMember(Name="search_linked_accounts", EmitDefaultValue=false)]
        public bool SearchLinkedAccounts { get; set; }

        /// <summary>
        /// Gets or Sets StorefrontHostname
        /// </summary>
        [DataMember(Name="storefront_hostname", EmitDefaultValue=false)]
        public string StorefrontHostname { get; set; }

        /// <summary>
        /// Wildcard search on the rule&#39;s text parameter (email / ip / bin / country / item id / avs codes - the backend disambiguates by rule_type).
        /// </summary>
        /// <value>Wildcard search on the rule&#39;s text parameter (email / ip / bin / country / item id / avs codes - the backend disambiguates by rule_type).</value>
        [DataMember(Name="text_value", EmitDefaultValue=false)]
        public string TextValue { get; set; }

        /// <summary>
        /// Gets or Sets ThemeCode
        /// </summary>
        [DataMember(Name="theme_code", EmitDefaultValue=false)]
        public string ThemeCode { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FraudRuleSearchRequest {\n");
            sb.Append("  AffiliateOidOrEmail: ").Append(AffiliateOidOrEmail).Append("\n");
            sb.Append("  AmountThresholdBegin: ").Append(AmountThresholdBegin).Append("\n");
            sb.Append("  AmountThresholdEnd: ").Append(AmountThresholdEnd).Append("\n");
            sb.Append("  AutoNote: ").Append(AutoNote).Append("\n");
            sb.Append("  CountThresholdBegin: ").Append(CountThresholdBegin).Append("\n");
            sb.Append("  CountThresholdEnd: ").Append(CountThresholdEnd).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  CreatedDateBegin: ").Append(CreatedDateBegin).Append("\n");
            sb.Append("  CreatedDateEnd: ").Append(CreatedDateEnd).Append("\n");
            sb.Append("  CreditCardPartial: ").Append(CreditCardPartial).Append("\n");
            sb.Append("  DeclineMessage: ").Append(DeclineMessage).Append("\n");
            sb.Append("  FailureAction: ").Append(FailureAction).Append("\n");
            sb.Append("  GatewayCode: ").Append(GatewayCode).Append("\n");
            sb.Append("  MerchantItemId: ").Append(MerchantItemId).Append("\n");
            sb.Append("  ModifierValue: ").Append(ModifierValue).Append("\n");
            sb.Append("  ModifyCustomField1: ").Append(ModifyCustomField1).Append("\n");
            sb.Append("  ModifyCustomField2: ").Append(ModifyCustomField2).Append("\n");
            sb.Append("  ModifyCustomField3: ").Append(ModifyCustomField3).Append("\n");
            sb.Append("  ModifyCustomField4: ").Append(ModifyCustomField4).Append("\n");
            sb.Append("  ModifyCustomField5: ").Append(ModifyCustomField5).Append("\n");
            sb.Append("  ModifyCustomField6: ").Append(ModifyCustomField6).Append("\n");
            sb.Append("  ModifyCustomField7: ").Append(ModifyCustomField7).Append("\n");
            sb.Append("  ModifySkipAffiliate: ").Append(ModifySkipAffiliate).Append("\n");
            sb.Append("  ModifySkipAffiliateNetworkPixel: ").Append(ModifySkipAffiliateNetworkPixel).Append("\n");
            sb.Append("  RuleGroup: ").Append(RuleGroup).Append("\n");
            sb.Append("  RuleType: ").Append(RuleType).Append("\n");
            sb.Append("  SearchLinkedAccounts: ").Append(SearchLinkedAccounts).Append("\n");
            sb.Append("  StorefrontHostname: ").Append(StorefrontHostname).Append("\n");
            sb.Append("  TextValue: ").Append(TextValue).Append("\n");
            sb.Append("  ThemeCode: ").Append(ThemeCode).Append("\n");
            sb.Append("  UserAction: ").Append(UserAction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FraudRuleSearchRequest);
        }

        /// <summary>
        /// Returns true if FraudRuleSearchRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of FraudRuleSearchRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FraudRuleSearchRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AffiliateOidOrEmail == input.AffiliateOidOrEmail ||
                    (this.AffiliateOidOrEmail != null &&
                    this.AffiliateOidOrEmail.Equals(input.AffiliateOidOrEmail))
                ) && 
                (
                    this.AmountThresholdBegin == input.AmountThresholdBegin ||
                    (this.AmountThresholdBegin != null &&
                    this.AmountThresholdBegin.Equals(input.AmountThresholdBegin))
                ) && 
                (
                    this.AmountThresholdEnd == input.AmountThresholdEnd ||
                    (this.AmountThresholdEnd != null &&
                    this.AmountThresholdEnd.Equals(input.AmountThresholdEnd))
                ) && 
                (
                    this.AutoNote == input.AutoNote ||
                    (this.AutoNote != null &&
                    this.AutoNote.Equals(input.AutoNote))
                ) && 
                (
                    this.CountThresholdBegin == input.CountThresholdBegin ||
                    (this.CountThresholdBegin != null &&
                    this.CountThresholdBegin.Equals(input.CountThresholdBegin))
                ) && 
                (
                    this.CountThresholdEnd == input.CountThresholdEnd ||
                    (this.CountThresholdEnd != null &&
                    this.CountThresholdEnd.Equals(input.CountThresholdEnd))
                ) && 
                (
                    this.CreatedBy == input.CreatedBy ||
                    (this.CreatedBy != null &&
                    this.CreatedBy.Equals(input.CreatedBy))
                ) && 
                (
                    this.CreatedDateBegin == input.CreatedDateBegin ||
                    (this.CreatedDateBegin != null &&
                    this.CreatedDateBegin.Equals(input.CreatedDateBegin))
                ) && 
                (
                    this.CreatedDateEnd == input.CreatedDateEnd ||
                    (this.CreatedDateEnd != null &&
                    this.CreatedDateEnd.Equals(input.CreatedDateEnd))
                ) && 
                (
                    this.CreditCardPartial == input.CreditCardPartial ||
                    (this.CreditCardPartial != null &&
                    this.CreditCardPartial.Equals(input.CreditCardPartial))
                ) && 
                (
                    this.DeclineMessage == input.DeclineMessage ||
                    (this.DeclineMessage != null &&
                    this.DeclineMessage.Equals(input.DeclineMessage))
                ) && 
                (
                    this.FailureAction == input.FailureAction ||
                    (this.FailureAction != null &&
                    this.FailureAction.Equals(input.FailureAction))
                ) && 
                (
                    this.GatewayCode == input.GatewayCode ||
                    (this.GatewayCode != null &&
                    this.GatewayCode.Equals(input.GatewayCode))
                ) && 
                (
                    this.MerchantItemId == input.MerchantItemId ||
                    (this.MerchantItemId != null &&
                    this.MerchantItemId.Equals(input.MerchantItemId))
                ) && 
                (
                    this.ModifierValue == input.ModifierValue ||
                    (this.ModifierValue != null &&
                    this.ModifierValue.Equals(input.ModifierValue))
                ) && 
                (
                    this.ModifyCustomField1 == input.ModifyCustomField1 ||
                    (this.ModifyCustomField1 != null &&
                    this.ModifyCustomField1.Equals(input.ModifyCustomField1))
                ) && 
                (
                    this.ModifyCustomField2 == input.ModifyCustomField2 ||
                    (this.ModifyCustomField2 != null &&
                    this.ModifyCustomField2.Equals(input.ModifyCustomField2))
                ) && 
                (
                    this.ModifyCustomField3 == input.ModifyCustomField3 ||
                    (this.ModifyCustomField3 != null &&
                    this.ModifyCustomField3.Equals(input.ModifyCustomField3))
                ) && 
                (
                    this.ModifyCustomField4 == input.ModifyCustomField4 ||
                    (this.ModifyCustomField4 != null &&
                    this.ModifyCustomField4.Equals(input.ModifyCustomField4))
                ) && 
                (
                    this.ModifyCustomField5 == input.ModifyCustomField5 ||
                    (this.ModifyCustomField5 != null &&
                    this.ModifyCustomField5.Equals(input.ModifyCustomField5))
                ) && 
                (
                    this.ModifyCustomField6 == input.ModifyCustomField6 ||
                    (this.ModifyCustomField6 != null &&
                    this.ModifyCustomField6.Equals(input.ModifyCustomField6))
                ) && 
                (
                    this.ModifyCustomField7 == input.ModifyCustomField7 ||
                    (this.ModifyCustomField7 != null &&
                    this.ModifyCustomField7.Equals(input.ModifyCustomField7))
                ) && 
                (
                    this.ModifySkipAffiliate == input.ModifySkipAffiliate ||
                    (this.ModifySkipAffiliate != null &&
                    this.ModifySkipAffiliate.Equals(input.ModifySkipAffiliate))
                ) && 
                (
                    this.ModifySkipAffiliateNetworkPixel == input.ModifySkipAffiliateNetworkPixel ||
                    (this.ModifySkipAffiliateNetworkPixel != null &&
                    this.ModifySkipAffiliateNetworkPixel.Equals(input.ModifySkipAffiliateNetworkPixel))
                ) && 
                (
                    this.RuleGroup == input.RuleGroup ||
                    (this.RuleGroup != null &&
                    this.RuleGroup.Equals(input.RuleGroup))
                ) && 
                (
                    this.RuleType == input.RuleType ||
                    (this.RuleType != null &&
                    this.RuleType.Equals(input.RuleType))
                ) && 
                (
                    this.SearchLinkedAccounts == input.SearchLinkedAccounts ||
                    (this.SearchLinkedAccounts != null &&
                    this.SearchLinkedAccounts.Equals(input.SearchLinkedAccounts))
                ) && 
                (
                    this.StorefrontHostname == input.StorefrontHostname ||
                    (this.StorefrontHostname != null &&
                    this.StorefrontHostname.Equals(input.StorefrontHostname))
                ) && 
                (
                    this.TextValue == input.TextValue ||
                    (this.TextValue != null &&
                    this.TextValue.Equals(input.TextValue))
                ) && 
                (
                    this.ThemeCode == input.ThemeCode ||
                    (this.ThemeCode != null &&
                    this.ThemeCode.Equals(input.ThemeCode))
                ) && 
                (
                    this.UserAction == input.UserAction ||
                    (this.UserAction != null &&
                    this.UserAction.Equals(input.UserAction))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AffiliateOidOrEmail != null)
                    hashCode = hashCode * 59 + this.AffiliateOidOrEmail.GetHashCode();
                if (this.AmountThresholdBegin != null)
                    hashCode = hashCode * 59 + this.AmountThresholdBegin.GetHashCode();
                if (this.AmountThresholdEnd != null)
                    hashCode = hashCode * 59 + this.AmountThresholdEnd.GetHashCode();
                if (this.AutoNote != null)
                    hashCode = hashCode * 59 + this.AutoNote.GetHashCode();
                if (this.CountThresholdBegin != null)
                    hashCode = hashCode * 59 + this.CountThresholdBegin.GetHashCode();
                if (this.CountThresholdEnd != null)
                    hashCode = hashCode * 59 + this.CountThresholdEnd.GetHashCode();
                if (this.CreatedBy != null)
                    hashCode = hashCode * 59 + this.CreatedBy.GetHashCode();
                if (this.CreatedDateBegin != null)
                    hashCode = hashCode * 59 + this.CreatedDateBegin.GetHashCode();
                if (this.CreatedDateEnd != null)
                    hashCode = hashCode * 59 + this.CreatedDateEnd.GetHashCode();
                if (this.CreditCardPartial != null)
                    hashCode = hashCode * 59 + this.CreditCardPartial.GetHashCode();
                if (this.DeclineMessage != null)
                    hashCode = hashCode * 59 + this.DeclineMessage.GetHashCode();
                if (this.FailureAction != null)
                    hashCode = hashCode * 59 + this.FailureAction.GetHashCode();
                if (this.GatewayCode != null)
                    hashCode = hashCode * 59 + this.GatewayCode.GetHashCode();
                if (this.MerchantItemId != null)
                    hashCode = hashCode * 59 + this.MerchantItemId.GetHashCode();
                if (this.ModifierValue != null)
                    hashCode = hashCode * 59 + this.ModifierValue.GetHashCode();
                if (this.ModifyCustomField1 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField1.GetHashCode();
                if (this.ModifyCustomField2 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField2.GetHashCode();
                if (this.ModifyCustomField3 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField3.GetHashCode();
                if (this.ModifyCustomField4 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField4.GetHashCode();
                if (this.ModifyCustomField5 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField5.GetHashCode();
                if (this.ModifyCustomField6 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField6.GetHashCode();
                if (this.ModifyCustomField7 != null)
                    hashCode = hashCode * 59 + this.ModifyCustomField7.GetHashCode();
                if (this.ModifySkipAffiliate != null)
                    hashCode = hashCode * 59 + this.ModifySkipAffiliate.GetHashCode();
                if (this.ModifySkipAffiliateNetworkPixel != null)
                    hashCode = hashCode * 59 + this.ModifySkipAffiliateNetworkPixel.GetHashCode();
                if (this.RuleGroup != null)
                    hashCode = hashCode * 59 + this.RuleGroup.GetHashCode();
                if (this.RuleType != null)
                    hashCode = hashCode * 59 + this.RuleType.GetHashCode();
                if (this.SearchLinkedAccounts != null)
                    hashCode = hashCode * 59 + this.SearchLinkedAccounts.GetHashCode();
                if (this.StorefrontHostname != null)
                    hashCode = hashCode * 59 + this.StorefrontHostname.GetHashCode();
                if (this.TextValue != null)
                    hashCode = hashCode * 59 + this.TextValue.GetHashCode();
                if (this.ThemeCode != null)
                    hashCode = hashCode * 59 + this.ThemeCode.GetHashCode();
                if (this.UserAction != null)
                    hashCode = hashCode * 59 + this.UserAction.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
