/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// IntegrationLog
    /// </summary>
    [DataContract]
    public partial class IntegrationLog :  IEquatable<IntegrationLog>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IntegrationLog" /> class.
        /// </summary>
        /// <param name="action">action.</param>
        /// <param name="direction">direction.</param>
        /// <param name="email">email.</param>
        /// <param name="files">files.</param>
        /// <param name="integrationLogOid">integrationLogOid.</param>
        /// <param name="itemId">itemId.</param>
        /// <param name="itemIpnOid">itemIpnOid.</param>
        /// <param name="logDts">Date/time the integration log was created.</param>
        /// <param name="logType">logType.</param>
        /// <param name="loggerId">loggerId.</param>
        /// <param name="loggerName">loggerName.</param>
        /// <param name="logs">logs.</param>
        /// <param name="omitLogMap">omitLogMap.</param>
        /// <param name="orderIds">orderIds.</param>
        /// <param name="pk">pk.</param>
        /// <param name="sk">sk.</param>
        /// <param name="status">status.</param>
        /// <param name="statusCode">statusCode.</param>
        public IntegrationLog(string action = default(string), string direction = default(string), string email = default(string), List<IntegrationLogFile> files = default(List<IntegrationLogFile>), int? integrationLogOid = default(int?), string itemId = default(string), int? itemIpnOid = default(int?), string logDts = default(string), string logType = default(string), string loggerId = default(string), string loggerName = default(string), List<IntegrationLogLog> logs = default(List<IntegrationLogLog>), bool? omitLogMap = default(bool?), List<string> orderIds = default(List<string>), string pk = default(string), string sk = default(string), string status = default(string), int? statusCode = default(int?))
        {
            this.Action = action;
            this.Direction = direction;
            this.Email = email;
            this.Files = files;
            this.IntegrationLogOid = integrationLogOid;
            this.ItemId = itemId;
            this.ItemIpnOid = itemIpnOid;
            this.LogDts = logDts;
            this.LogType = logType;
            this.LoggerId = loggerId;
            this.LoggerName = loggerName;
            this.Logs = logs;
            this.OmitLogMap = omitLogMap;
            this.OrderIds = orderIds;
            this.Pk = pk;
            this.Sk = sk;
            this.Status = status;
            this.StatusCode = statusCode;
        }
        
        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name="action", EmitDefaultValue=false)]
        public string Action { get; set; }

        /// <summary>
        /// Gets or Sets Direction
        /// </summary>
        [DataMember(Name="direction", EmitDefaultValue=false)]
        public string Direction { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name="files", EmitDefaultValue=false)]
        public List<IntegrationLogFile> Files { get; set; }

        /// <summary>
        /// Gets or Sets IntegrationLogOid
        /// </summary>
        [DataMember(Name="integration_log_oid", EmitDefaultValue=false)]
        public int? IntegrationLogOid { get; set; }

        /// <summary>
        /// Gets or Sets ItemId
        /// </summary>
        [DataMember(Name="item_id", EmitDefaultValue=false)]
        public string ItemId { get; set; }

        /// <summary>
        /// Gets or Sets ItemIpnOid
        /// </summary>
        [DataMember(Name="item_ipn_oid", EmitDefaultValue=false)]
        public int? ItemIpnOid { get; set; }

        /// <summary>
        /// Date/time the integration log was created
        /// </summary>
        /// <value>Date/time the integration log was created</value>
        [DataMember(Name="log_dts", EmitDefaultValue=false)]
        public string LogDts { get; set; }

        /// <summary>
        /// Gets or Sets LogType
        /// </summary>
        [DataMember(Name="log_type", EmitDefaultValue=false)]
        public string LogType { get; set; }

        /// <summary>
        /// Gets or Sets LoggerId
        /// </summary>
        [DataMember(Name="logger_id", EmitDefaultValue=false)]
        public string LoggerId { get; set; }

        /// <summary>
        /// Gets or Sets LoggerName
        /// </summary>
        [DataMember(Name="logger_name", EmitDefaultValue=false)]
        public string LoggerName { get; set; }

        /// <summary>
        /// Gets or Sets Logs
        /// </summary>
        [DataMember(Name="logs", EmitDefaultValue=false)]
        public List<IntegrationLogLog> Logs { get; set; }

        /// <summary>
        /// Gets or Sets OmitLogMap
        /// </summary>
        [DataMember(Name="omit_log_map", EmitDefaultValue=false)]
        public bool? OmitLogMap { get; set; }

        /// <summary>
        /// Gets or Sets OrderIds
        /// </summary>
        [DataMember(Name="order_ids", EmitDefaultValue=false)]
        public List<string> OrderIds { get; set; }

        /// <summary>
        /// Gets or Sets Pk
        /// </summary>
        [DataMember(Name="pk", EmitDefaultValue=false)]
        public string Pk { get; set; }

        /// <summary>
        /// Gets or Sets Sk
        /// </summary>
        [DataMember(Name="sk", EmitDefaultValue=false)]
        public string Sk { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets StatusCode
        /// </summary>
        [DataMember(Name="status_code", EmitDefaultValue=false)]
        public int? StatusCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IntegrationLog {\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  IntegrationLogOid: ").Append(IntegrationLogOid).Append("\n");
            sb.Append("  ItemId: ").Append(ItemId).Append("\n");
            sb.Append("  ItemIpnOid: ").Append(ItemIpnOid).Append("\n");
            sb.Append("  LogDts: ").Append(LogDts).Append("\n");
            sb.Append("  LogType: ").Append(LogType).Append("\n");
            sb.Append("  LoggerId: ").Append(LoggerId).Append("\n");
            sb.Append("  LoggerName: ").Append(LoggerName).Append("\n");
            sb.Append("  Logs: ").Append(Logs).Append("\n");
            sb.Append("  OmitLogMap: ").Append(OmitLogMap).Append("\n");
            sb.Append("  OrderIds: ").Append(OrderIds).Append("\n");
            sb.Append("  Pk: ").Append(Pk).Append("\n");
            sb.Append("  Sk: ").Append(Sk).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IntegrationLog);
        }

        /// <summary>
        /// Returns true if IntegrationLog instances are equal
        /// </summary>
        /// <param name="input">Instance of IntegrationLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IntegrationLog input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Action == input.Action ||
                    (this.Action != null &&
                    this.Action.Equals(input.Action))
                ) && 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Files == input.Files ||
                    this.Files != null &&
                    this.Files.SequenceEqual(input.Files)
                ) && 
                (
                    this.IntegrationLogOid == input.IntegrationLogOid ||
                    (this.IntegrationLogOid != null &&
                    this.IntegrationLogOid.Equals(input.IntegrationLogOid))
                ) && 
                (
                    this.ItemId == input.ItemId ||
                    (this.ItemId != null &&
                    this.ItemId.Equals(input.ItemId))
                ) && 
                (
                    this.ItemIpnOid == input.ItemIpnOid ||
                    (this.ItemIpnOid != null &&
                    this.ItemIpnOid.Equals(input.ItemIpnOid))
                ) && 
                (
                    this.LogDts == input.LogDts ||
                    (this.LogDts != null &&
                    this.LogDts.Equals(input.LogDts))
                ) && 
                (
                    this.LogType == input.LogType ||
                    (this.LogType != null &&
                    this.LogType.Equals(input.LogType))
                ) && 
                (
                    this.LoggerId == input.LoggerId ||
                    (this.LoggerId != null &&
                    this.LoggerId.Equals(input.LoggerId))
                ) && 
                (
                    this.LoggerName == input.LoggerName ||
                    (this.LoggerName != null &&
                    this.LoggerName.Equals(input.LoggerName))
                ) && 
                (
                    this.Logs == input.Logs ||
                    this.Logs != null &&
                    this.Logs.SequenceEqual(input.Logs)
                ) && 
                (
                    this.OmitLogMap == input.OmitLogMap ||
                    (this.OmitLogMap != null &&
                    this.OmitLogMap.Equals(input.OmitLogMap))
                ) && 
                (
                    this.OrderIds == input.OrderIds ||
                    this.OrderIds != null &&
                    this.OrderIds.SequenceEqual(input.OrderIds)
                ) && 
                (
                    this.Pk == input.Pk ||
                    (this.Pk != null &&
                    this.Pk.Equals(input.Pk))
                ) && 
                (
                    this.Sk == input.Sk ||
                    (this.Sk != null &&
                    this.Sk.Equals(input.Sk))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.StatusCode == input.StatusCode ||
                    (this.StatusCode != null &&
                    this.StatusCode.Equals(input.StatusCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Action != null)
                    hashCode = hashCode * 59 + this.Action.GetHashCode();
                if (this.Direction != null)
                    hashCode = hashCode * 59 + this.Direction.GetHashCode();
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Files != null)
                    hashCode = hashCode * 59 + this.Files.GetHashCode();
                if (this.IntegrationLogOid != null)
                    hashCode = hashCode * 59 + this.IntegrationLogOid.GetHashCode();
                if (this.ItemId != null)
                    hashCode = hashCode * 59 + this.ItemId.GetHashCode();
                if (this.ItemIpnOid != null)
                    hashCode = hashCode * 59 + this.ItemIpnOid.GetHashCode();
                if (this.LogDts != null)
                    hashCode = hashCode * 59 + this.LogDts.GetHashCode();
                if (this.LogType != null)
                    hashCode = hashCode * 59 + this.LogType.GetHashCode();
                if (this.LoggerId != null)
                    hashCode = hashCode * 59 + this.LoggerId.GetHashCode();
                if (this.LoggerName != null)
                    hashCode = hashCode * 59 + this.LoggerName.GetHashCode();
                if (this.Logs != null)
                    hashCode = hashCode * 59 + this.Logs.GetHashCode();
                if (this.OmitLogMap != null)
                    hashCode = hashCode * 59 + this.OmitLogMap.GetHashCode();
                if (this.OrderIds != null)
                    hashCode = hashCode * 59 + this.OrderIds.GetHashCode();
                if (this.Pk != null)
                    hashCode = hashCode * 59 + this.Pk.GetHashCode();
                if (this.Sk != null)
                    hashCode = hashCode * 59 + this.Sk.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.StatusCode != null)
                    hashCode = hashCode * 59 + this.StatusCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
