/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ItemShippingCase
    /// </summary>
    [DataContract]
    public partial class ItemShippingCase :  IEquatable<ItemShippingCase>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemShippingCase" /> class.
        /// </summary>
        /// <param name="CaseLabel">CaseLabel.</param>
        /// <param name="CaseMerchantItemId">CaseMerchantItemId.</param>
        /// <param name="CaseMerchantItemOid">CaseMerchantItemOid.</param>
        /// <param name="Quantity">Quantity.</param>
        public ItemShippingCase(string CaseLabel = null, string CaseMerchantItemId = null, int? CaseMerchantItemOid = null, int? Quantity = null)
        {
            this.CaseLabel = CaseLabel;
            this.CaseMerchantItemId = CaseMerchantItemId;
            this.CaseMerchantItemOid = CaseMerchantItemOid;
            this.Quantity = Quantity;
        }
        
        /// <summary>
        /// Gets or Sets CaseLabel
        /// </summary>
        [DataMember(Name="case_label", EmitDefaultValue=false)]
        public string CaseLabel { get; set; }
        /// <summary>
        /// Gets or Sets CaseMerchantItemId
        /// </summary>
        [DataMember(Name="case_merchant_item_id", EmitDefaultValue=false)]
        public string CaseMerchantItemId { get; set; }
        /// <summary>
        /// Gets or Sets CaseMerchantItemOid
        /// </summary>
        [DataMember(Name="case_merchant_item_oid", EmitDefaultValue=false)]
        public int? CaseMerchantItemOid { get; set; }
        /// <summary>
        /// Gets or Sets Quantity
        /// </summary>
        [DataMember(Name="quantity", EmitDefaultValue=false)]
        public int? Quantity { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemShippingCase {\n");
            sb.Append("  CaseLabel: ").Append(CaseLabel).Append("\n");
            sb.Append("  CaseMerchantItemId: ").Append(CaseMerchantItemId).Append("\n");
            sb.Append("  CaseMerchantItemOid: ").Append(CaseMerchantItemOid).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ItemShippingCase);
        }

        /// <summary>
        /// Returns true if ItemShippingCase instances are equal
        /// </summary>
        /// <param name="other">Instance of ItemShippingCase to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemShippingCase other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CaseLabel == other.CaseLabel ||
                    this.CaseLabel != null &&
                    this.CaseLabel.Equals(other.CaseLabel)
                ) && 
                (
                    this.CaseMerchantItemId == other.CaseMerchantItemId ||
                    this.CaseMerchantItemId != null &&
                    this.CaseMerchantItemId.Equals(other.CaseMerchantItemId)
                ) && 
                (
                    this.CaseMerchantItemOid == other.CaseMerchantItemOid ||
                    this.CaseMerchantItemOid != null &&
                    this.CaseMerchantItemOid.Equals(other.CaseMerchantItemOid)
                ) && 
                (
                    this.Quantity == other.Quantity ||
                    this.Quantity != null &&
                    this.Quantity.Equals(other.Quantity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CaseLabel != null)
                    hash = hash * 59 + this.CaseLabel.GetHashCode();
                if (this.CaseMerchantItemId != null)
                    hash = hash * 59 + this.CaseMerchantItemId.GetHashCode();
                if (this.CaseMerchantItemOid != null)
                    hash = hash * 59 + this.CaseMerchantItemOid.GetHashCode();
                if (this.Quantity != null)
                    hash = hash * 59 + this.Quantity.GetHashCode();
                return hash;
            }
        }
    }

}
