/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ItemFulfillmentAddon
    /// </summary>
    [DataContract]
    public partial class ItemFulfillmentAddon :  IEquatable<ItemFulfillmentAddon>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemFulfillmentAddon" /> class.
        /// </summary>
        /// <param name="addItemId">Add Item Id.</param>
        /// <param name="addItemOid">Add Item object identifier.</param>
        /// <param name="oncePerOrder">Quantity.</param>
        /// <param name="quantity">Quantity.</param>
        public ItemFulfillmentAddon(string addItemId = default(string), int addItemOid = default(int), bool oncePerOrder = default(bool), int quantity = default(int))
        {
            this.AddItemId = addItemId;
            this.AddItemOid = addItemOid;
            this.OncePerOrder = oncePerOrder;
            this.Quantity = quantity;
        }

        /// <summary>
        /// Add Item Id
        /// </summary>
        /// <value>Add Item Id</value>
        [DataMember(Name="add_item_id", EmitDefaultValue=false)]
        public string AddItemId { get; set; }

        /// <summary>
        /// Add Item object identifier
        /// </summary>
        /// <value>Add Item object identifier</value>
        [DataMember(Name="add_item_oid", EmitDefaultValue=false)]
        public int AddItemOid { get; set; }

        /// <summary>
        /// Quantity
        /// </summary>
        /// <value>Quantity</value>
        [DataMember(Name="once_per_order", EmitDefaultValue=false)]
        public bool OncePerOrder { get; set; }

        /// <summary>
        /// Quantity
        /// </summary>
        /// <value>Quantity</value>
        [DataMember(Name="quantity", EmitDefaultValue=false)]
        public int Quantity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemFulfillmentAddon {\n");
            sb.Append("  AddItemId: ").Append(AddItemId).Append("\n");
            sb.Append("  AddItemOid: ").Append(AddItemOid).Append("\n");
            sb.Append("  OncePerOrder: ").Append(OncePerOrder).Append("\n");
            sb.Append("  Quantity: ").Append(Quantity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ItemFulfillmentAddon);
        }

        /// <summary>
        /// Returns true if ItemFulfillmentAddon instances are equal
        /// </summary>
        /// <param name="input">Instance of ItemFulfillmentAddon to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemFulfillmentAddon input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AddItemId == input.AddItemId ||
                    (this.AddItemId != null &&
                    this.AddItemId.Equals(input.AddItemId))
                ) && 
                (
                    this.AddItemOid == input.AddItemOid ||
                    (this.AddItemOid != null &&
                    this.AddItemOid.Equals(input.AddItemOid))
                ) && 
                (
                    this.OncePerOrder == input.OncePerOrder ||
                    (this.OncePerOrder != null &&
                    this.OncePerOrder.Equals(input.OncePerOrder))
                ) && 
                (
                    this.Quantity == input.Quantity ||
                    (this.Quantity != null &&
                    this.Quantity.Equals(input.Quantity))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AddItemId != null)
                    hashCode = hashCode * 59 + this.AddItemId.GetHashCode();
                if (this.AddItemOid != null)
                    hashCode = hashCode * 59 + this.AddItemOid.GetHashCode();
                if (this.OncePerOrder != null)
                    hashCode = hashCode * 59 + this.OncePerOrder.GetHashCode();
                if (this.Quantity != null)
                    hashCode = hashCode * 59 + this.Quantity.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
