/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ItemPricingTier
    /// </summary>
    [DataContract]
    public partial class ItemPricingTier :  IEquatable<ItemPricingTier>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemPricingTier" /> class.
        /// </summary>
        /// <param name="DefaultTier">DefaultTier.</param>
        /// <param name="Discounts">Discounts.</param>
        /// <param name="Limit">Limit.</param>
        /// <param name="Name">Name.</param>
        /// <param name="PricingTierOid">PricingTierOid.</param>
        public ItemPricingTier(bool? DefaultTier = null, List<ItemPricingTierDiscount> Discounts = null, ItemPricingTierLimit Limit = null, string Name = null, int? PricingTierOid = null)
        {
            this.DefaultTier = DefaultTier;
            this.Discounts = Discounts;
            this.Limit = Limit;
            this.Name = Name;
            this.PricingTierOid = PricingTierOid;
        }
        
        /// <summary>
        /// Gets or Sets DefaultTier
        /// </summary>
        [DataMember(Name="default_tier", EmitDefaultValue=false)]
        public bool? DefaultTier { get; set; }
        /// <summary>
        /// Gets or Sets Discounts
        /// </summary>
        [DataMember(Name="discounts", EmitDefaultValue=false)]
        public List<ItemPricingTierDiscount> Discounts { get; set; }
        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name="limit", EmitDefaultValue=false)]
        public ItemPricingTierLimit Limit { get; set; }
        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// Gets or Sets PricingTierOid
        /// </summary>
        [DataMember(Name="pricing_tier_oid", EmitDefaultValue=false)]
        public int? PricingTierOid { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemPricingTier {\n");
            sb.Append("  DefaultTier: ").Append(DefaultTier).Append("\n");
            sb.Append("  Discounts: ").Append(Discounts).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PricingTierOid: ").Append(PricingTierOid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ItemPricingTier);
        }

        /// <summary>
        /// Returns true if ItemPricingTier instances are equal
        /// </summary>
        /// <param name="other">Instance of ItemPricingTier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemPricingTier other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DefaultTier == other.DefaultTier ||
                    this.DefaultTier != null &&
                    this.DefaultTier.Equals(other.DefaultTier)
                ) && 
                (
                    this.Discounts == other.Discounts ||
                    this.Discounts != null &&
                    this.Discounts.SequenceEqual(other.Discounts)
                ) && 
                (
                    this.Limit == other.Limit ||
                    this.Limit != null &&
                    this.Limit.Equals(other.Limit)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.PricingTierOid == other.PricingTierOid ||
                    this.PricingTierOid != null &&
                    this.PricingTierOid.Equals(other.PricingTierOid)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DefaultTier != null)
                    hash = hash * 59 + this.DefaultTier.GetHashCode();
                if (this.Discounts != null)
                    hash = hash * 59 + this.Discounts.GetHashCode();
                if (this.Limit != null)
                    hash = hash * 59 + this.Limit.GetHashCode();
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.PricingTierOid != null)
                    hash = hash * 59 + this.PricingTierOid.GetHashCode();
                return hash;
            }
        }
    }

}
