/* 
 * UltraCart Rest API V2
 *
 * This is the next generation UltraCart REST API...
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// ItemAutoOrderStepGrandfatherPricing
    /// </summary>
    [DataContract]
    public partial class ItemAutoOrderStepGrandfatherPricing :  IEquatable<ItemAutoOrderStepGrandfatherPricing>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ItemAutoOrderStepGrandfatherPricing" /> class.
        /// </summary>
        /// <param name="OnOrBeforeDate">OnOrBeforeDate.</param>
        /// <param name="UnitCost">UnitCost.</param>
        public ItemAutoOrderStepGrandfatherPricing(string OnOrBeforeDate = null, double? UnitCost = null)
        {
            this.OnOrBeforeDate = OnOrBeforeDate;
            this.UnitCost = UnitCost;
        }
        
        /// <summary>
        /// Gets or Sets OnOrBeforeDate
        /// </summary>
        [DataMember(Name="on_or_before_date", EmitDefaultValue=false)]
        public string OnOrBeforeDate { get; set; }
        /// <summary>
        /// Gets or Sets UnitCost
        /// </summary>
        [DataMember(Name="unit_cost", EmitDefaultValue=false)]
        public double? UnitCost { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ItemAutoOrderStepGrandfatherPricing {\n");
            sb.Append("  OnOrBeforeDate: ").Append(OnOrBeforeDate).Append("\n");
            sb.Append("  UnitCost: ").Append(UnitCost).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ItemAutoOrderStepGrandfatherPricing);
        }

        /// <summary>
        /// Returns true if ItemAutoOrderStepGrandfatherPricing instances are equal
        /// </summary>
        /// <param name="other">Instance of ItemAutoOrderStepGrandfatherPricing to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ItemAutoOrderStepGrandfatherPricing other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.OnOrBeforeDate == other.OnOrBeforeDate ||
                    this.OnOrBeforeDate != null &&
                    this.OnOrBeforeDate.Equals(other.OnOrBeforeDate)
                ) && 
                (
                    this.UnitCost == other.UnitCost ||
                    this.UnitCost != null &&
                    this.UnitCost.Equals(other.UnitCost)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.OnOrBeforeDate != null)
                    hash = hash * 59 + this.OnOrBeforeDate.GetHashCode();
                if (this.UnitCost != null)
                    hash = hash * 59 + this.UnitCost.GetHashCode();
                return hash;
            }
        }
    }

}
