/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// OrderByTokenQuery
    /// </summary>
    [DataContract]
    public partial class OrderByTokenQuery :  IEquatable<OrderByTokenQuery>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderByTokenQuery" /> class.
        /// </summary>
        /// <param name="orderToken">Order Token.</param>
        public OrderByTokenQuery(string orderToken = default(string))
        {
            this.OrderToken = orderToken;
        }

        /// <summary>
        /// Order Token
        /// </summary>
        /// <value>Order Token</value>
        [DataMember(Name="order_token", EmitDefaultValue=false)]
        public string OrderToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderByTokenQuery {\n");
            sb.Append("  OrderToken: ").Append(OrderToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrderByTokenQuery);
        }

        /// <summary>
        /// Returns true if OrderByTokenQuery instances are equal
        /// </summary>
        /// <param name="input">Instance of OrderByTokenQuery to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderByTokenQuery input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OrderToken == input.OrderToken ||
                    (this.OrderToken != null &&
                    this.OrderToken.Equals(input.OrderToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderToken != null)
                    hashCode = hashCode * 59 + this.OrderToken.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
