/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// PaymentsConfigurationMoneyOrder
    /// </summary>
    [DataContract]
    public partial class PaymentsConfigurationMoneyOrder :  IEquatable<PaymentsConfigurationMoneyOrder>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentsConfigurationMoneyOrder" /> class.
        /// </summary>
        /// <param name="acceptMoneyOrders">acceptMoneyOrders.</param>
        /// <param name="restrictions">restrictions.</param>
        public PaymentsConfigurationMoneyOrder(bool? acceptMoneyOrders = default(bool?), PaymentsConfigurationRestrictions restrictions = default(PaymentsConfigurationRestrictions))
        {
            this.AcceptMoneyOrders = acceptMoneyOrders;
            this.Restrictions = restrictions;
        }
        
        /// <summary>
        /// Gets or Sets AcceptMoneyOrders
        /// </summary>
        [DataMember(Name="acceptMoneyOrders", EmitDefaultValue=false)]
        public bool? AcceptMoneyOrders { get; set; }

        /// <summary>
        /// Gets or Sets Restrictions
        /// </summary>
        [DataMember(Name="restrictions", EmitDefaultValue=false)]
        public PaymentsConfigurationRestrictions Restrictions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentsConfigurationMoneyOrder {\n");
            sb.Append("  AcceptMoneyOrders: ").Append(AcceptMoneyOrders).Append("\n");
            sb.Append("  Restrictions: ").Append(Restrictions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentsConfigurationMoneyOrder);
        }

        /// <summary>
        /// Returns true if PaymentsConfigurationMoneyOrder instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentsConfigurationMoneyOrder to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentsConfigurationMoneyOrder input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AcceptMoneyOrders == input.AcceptMoneyOrders ||
                    (this.AcceptMoneyOrders != null &&
                    this.AcceptMoneyOrders.Equals(input.AcceptMoneyOrders))
                ) && 
                (
                    this.Restrictions == input.Restrictions ||
                    (this.Restrictions != null &&
                    this.Restrictions.Equals(input.Restrictions))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AcceptMoneyOrders != null)
                    hashCode = hashCode * 59 + this.AcceptMoneyOrders.GetHashCode();
                if (this.Restrictions != null)
                    hashCode = hashCode * 59 + this.Restrictions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
