/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// SfvbLibraryInstallRequest
    /// </summary>
    [DataContract]
    public partial class SfvbLibraryInstallRequest :  IEquatable<SfvbLibraryInstallRequest>, IValidatableObject
    {
        /// <summary>
        /// What to do when a file the entry installs already exists with different content.  fail refuses and writes nothing, skip keeps the existing file, overwrite replaces it.
        /// </summary>
        /// <value>What to do when a file the entry installs already exists with different content.  fail refuses and writes nothing, skip keeps the existing file, overwrite replaces it.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OnConflictEnum
        {
            /// <summary>
            /// Enum Fail for value: fail
            /// </summary>
            [EnumMember(Value = "fail")]
            Fail = 1,

            /// <summary>
            /// Enum Skip for value: skip
            /// </summary>
            [EnumMember(Value = "skip")]
            Skip = 2,

            /// <summary>
            /// Enum Overwrite for value: overwrite
            /// </summary>
            [EnumMember(Value = "overwrite")]
            Overwrite = 3

        }

        /// <summary>
        /// What to do when a file the entry installs already exists with different content.  fail refuses and writes nothing, skip keeps the existing file, overwrite replaces it.
        /// </summary>
        /// <value>What to do when a file the entry installs already exists with different content.  fail refuses and writes nothing, skip keeps the existing file, overwrite replaces it.</value>
        [DataMember(Name="on_conflict", EmitDefaultValue=false)]
        public OnConflictEnum? OnConflict { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SfvbLibraryInstallRequest" /> class.
        /// </summary>
        /// <param name="acknowledgeExecutable">Must be true to install an entry whose content_manifest lists executable content.  Read the manifest first..</param>
        /// <param name="onConflict">What to do when a file the entry installs already exists with different content.  fail refuses and writes nothing, skip keeps the existing file, overwrite replaces it..</param>
        /// <param name="revisionNumber">A published revision to install.  Defaults to the latest one, or the draft for the owner..</param>
        public SfvbLibraryInstallRequest(bool acknowledgeExecutable = default(bool), OnConflictEnum? onConflict = default(OnConflictEnum?), int revisionNumber = default(int))
        {
            this.AcknowledgeExecutable = acknowledgeExecutable;
            this.OnConflict = onConflict;
            this.RevisionNumber = revisionNumber;
        }

        /// <summary>
        /// Must be true to install an entry whose content_manifest lists executable content.  Read the manifest first.
        /// </summary>
        /// <value>Must be true to install an entry whose content_manifest lists executable content.  Read the manifest first.</value>
        [DataMember(Name="acknowledge_executable", EmitDefaultValue=false)]
        public bool AcknowledgeExecutable { get; set; }


        /// <summary>
        /// A published revision to install.  Defaults to the latest one, or the draft for the owner.
        /// </summary>
        /// <value>A published revision to install.  Defaults to the latest one, or the draft for the owner.</value>
        [DataMember(Name="revision_number", EmitDefaultValue=false)]
        public int RevisionNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SfvbLibraryInstallRequest {\n");
            sb.Append("  AcknowledgeExecutable: ").Append(AcknowledgeExecutable).Append("\n");
            sb.Append("  OnConflict: ").Append(OnConflict).Append("\n");
            sb.Append("  RevisionNumber: ").Append(RevisionNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SfvbLibraryInstallRequest);
        }

        /// <summary>
        /// Returns true if SfvbLibraryInstallRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SfvbLibraryInstallRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SfvbLibraryInstallRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AcknowledgeExecutable == input.AcknowledgeExecutable ||
                    (this.AcknowledgeExecutable != null &&
                    this.AcknowledgeExecutable.Equals(input.AcknowledgeExecutable))
                ) && 
                (
                    this.OnConflict == input.OnConflict ||
                    (this.OnConflict != null &&
                    this.OnConflict.Equals(input.OnConflict))
                ) && 
                (
                    this.RevisionNumber == input.RevisionNumber ||
                    (this.RevisionNumber != null &&
                    this.RevisionNumber.Equals(input.RevisionNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AcknowledgeExecutable != null)
                    hashCode = hashCode * 59 + this.AcknowledgeExecutable.GetHashCode();
                if (this.OnConflict != null)
                    hashCode = hashCode * 59 + this.OnConflict.GetHashCode();
                if (this.RevisionNumber != null)
                    hashCode = hashCode * 59 + this.RevisionNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
