/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// SfvbPageDuplicateRequest
    /// </summary>
    [DataContract]
    public partial class SfvbPageDuplicateRequest :  IEquatable<SfvbPageDuplicateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SfvbPageDuplicateRequest" /> class.
        /// </summary>
        /// <param name="path">Path of the copy, for example /lp/spring-sale-b/.  The same rules as creating a page - the parent must exist, the path must be new, and the last part may only contain letters, digits, hyphens and underscores..</param>
        /// <param name="sourcePath">Path of the page to copy.  Not the root, and not a page with pages under it..</param>
        /// <param name="title">Title of the copy.  Defaults to the source page&#39;s title..</param>
        public SfvbPageDuplicateRequest(string path = default(string), string sourcePath = default(string), string title = default(string))
        {
            this.Path = path;
            this.SourcePath = sourcePath;
            this.Title = title;
        }

        /// <summary>
        /// Path of the copy, for example /lp/spring-sale-b/.  The same rules as creating a page - the parent must exist, the path must be new, and the last part may only contain letters, digits, hyphens and underscores.
        /// </summary>
        /// <value>Path of the copy, for example /lp/spring-sale-b/.  The same rules as creating a page - the parent must exist, the path must be new, and the last part may only contain letters, digits, hyphens and underscores.</value>
        [DataMember(Name="path", EmitDefaultValue=false)]
        public string Path { get; set; }

        /// <summary>
        /// Path of the page to copy.  Not the root, and not a page with pages under it.
        /// </summary>
        /// <value>Path of the page to copy.  Not the root, and not a page with pages under it.</value>
        [DataMember(Name="source_path", EmitDefaultValue=false)]
        public string SourcePath { get; set; }

        /// <summary>
        /// Title of the copy.  Defaults to the source page&#39;s title.
        /// </summary>
        /// <value>Title of the copy.  Defaults to the source page&#39;s title.</value>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SfvbPageDuplicateRequest {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  SourcePath: ").Append(SourcePath).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SfvbPageDuplicateRequest);
        }

        /// <summary>
        /// Returns true if SfvbPageDuplicateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SfvbPageDuplicateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SfvbPageDuplicateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.SourcePath == input.SourcePath ||
                    (this.SourcePath != null &&
                    this.SourcePath.Equals(input.SourcePath))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Path != null)
                    hashCode = hashCode * 59 + this.Path.GetHashCode();
                if (this.SourcePath != null)
                    hashCode = hashCode * 59 + this.SourcePath.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
