/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// SfvbPageBlogPostsRequest
    /// </summary>
    [DataContract]
    public partial class SfvbPageBlogPostsRequest :  IEquatable<SfvbPageBlogPostsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SfvbPageBlogPostsRequest" /> class.
        /// </summary>
        /// <param name="blogPostOids">Blog post oids from the blog post list, at most 500..</param>
        public SfvbPageBlogPostsRequest(List<int> blogPostOids = default(List<int>))
        {
            this.BlogPostOids = blogPostOids;
        }

        /// <summary>
        /// Blog post oids from the blog post list, at most 500.
        /// </summary>
        /// <value>Blog post oids from the blog post list, at most 500.</value>
        [DataMember(Name="blog_post_oids", EmitDefaultValue=false)]
        public List<int> BlogPostOids { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SfvbPageBlogPostsRequest {\n");
            sb.Append("  BlogPostOids: ").Append(BlogPostOids).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SfvbPageBlogPostsRequest);
        }

        /// <summary>
        /// Returns true if SfvbPageBlogPostsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SfvbPageBlogPostsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SfvbPageBlogPostsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.BlogPostOids == input.BlogPostOids ||
                    this.BlogPostOids != null &&
                    input.BlogPostOids != null &&
                    this.BlogPostOids.SequenceEqual(input.BlogPostOids)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.BlogPostOids != null)
                    hashCode = hashCode * 59 + this.BlogPostOids.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
