/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// SfvbNotFoundHit
    /// </summary>
    [DataContract]
    public partial class SfvbNotFoundHit :  IEquatable<SfvbNotFoundHit>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SfvbNotFoundHit" /> class.
        /// </summary>
        /// <param name="bot">True when the hit was from a bot..</param>
        /// <param name="referrerHost">Host of the linking page..</param>
        /// <param name="requestDts">When, ISO 8601..</param>
        /// <param name="userAgent">The browser or bot..</param>
        public SfvbNotFoundHit(bool bot = default(bool), string referrerHost = default(string), string requestDts = default(string), string userAgent = default(string))
        {
            this.Bot = bot;
            this.ReferrerHost = referrerHost;
            this.RequestDts = requestDts;
            this.UserAgent = userAgent;
        }

        /// <summary>
        /// True when the hit was from a bot.
        /// </summary>
        /// <value>True when the hit was from a bot.</value>
        [DataMember(Name="bot", EmitDefaultValue=false)]
        public bool Bot { get; set; }

        /// <summary>
        /// Host of the linking page.
        /// </summary>
        /// <value>Host of the linking page.</value>
        [DataMember(Name="referrer_host", EmitDefaultValue=false)]
        public string ReferrerHost { get; set; }

        /// <summary>
        /// When, ISO 8601.
        /// </summary>
        /// <value>When, ISO 8601.</value>
        [DataMember(Name="request_dts", EmitDefaultValue=false)]
        public string RequestDts { get; set; }

        /// <summary>
        /// The browser or bot.
        /// </summary>
        /// <value>The browser or bot.</value>
        [DataMember(Name="user_agent", EmitDefaultValue=false)]
        public string UserAgent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SfvbNotFoundHit {\n");
            sb.Append("  Bot: ").Append(Bot).Append("\n");
            sb.Append("  ReferrerHost: ").Append(ReferrerHost).Append("\n");
            sb.Append("  RequestDts: ").Append(RequestDts).Append("\n");
            sb.Append("  UserAgent: ").Append(UserAgent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SfvbNotFoundHit);
        }

        /// <summary>
        /// Returns true if SfvbNotFoundHit instances are equal
        /// </summary>
        /// <param name="input">Instance of SfvbNotFoundHit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SfvbNotFoundHit input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bot == input.Bot ||
                    (this.Bot != null &&
                    this.Bot.Equals(input.Bot))
                ) && 
                (
                    this.ReferrerHost == input.ReferrerHost ||
                    (this.ReferrerHost != null &&
                    this.ReferrerHost.Equals(input.ReferrerHost))
                ) && 
                (
                    this.RequestDts == input.RequestDts ||
                    (this.RequestDts != null &&
                    this.RequestDts.Equals(input.RequestDts))
                ) && 
                (
                    this.UserAgent == input.UserAgent ||
                    (this.UserAgent != null &&
                    this.UserAgent.Equals(input.UserAgent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bot != null)
                    hashCode = hashCode * 59 + this.Bot.GetHashCode();
                if (this.ReferrerHost != null)
                    hashCode = hashCode * 59 + this.ReferrerHost.GetHashCode();
                if (this.RequestDts != null)
                    hashCode = hashCode * 59 + this.RequestDts.GetHashCode();
                if (this.UserAgent != null)
                    hashCode = hashCode * 59 + this.UserAgent.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
