/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = com.ultracart.admin.v2.Client.SwaggerDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// TaxProvidersResponse
    /// </summary>
    [DataContract]
    public partial class TaxProvidersResponse :  IEquatable<TaxProvidersResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TaxProvidersResponse" /> class.
        /// </summary>
        /// <param name="avalara">avalara.</param>
        /// <param name="error">error.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="self">self.</param>
        /// <param name="sovos">sovos.</param>
        /// <param name="success">Indicates if API call was successful.</param>
        /// <param name="taxjar">taxjar.</param>
        /// <param name="ultracart">ultracart.</param>
        /// <param name="warning">warning.</param>
        public TaxProvidersResponse(TaxProviderAvalara avalara = default(TaxProviderAvalara), Error error = default(Error), ResponseMetadata metadata = default(ResponseMetadata), TaxProviderSelf self = default(TaxProviderSelf), TaxProviderSovos sovos = default(TaxProviderSovos), bool? success = default(bool?), TaxProviderTaxJar taxjar = default(TaxProviderTaxJar), TaxProviderUltraCart ultracart = default(TaxProviderUltraCart), Warning warning = default(Warning))
        {
            this.Avalara = avalara;
            this.Error = error;
            this.Metadata = metadata;
            this.Self = self;
            this.Sovos = sovos;
            this.Success = success;
            this.Taxjar = taxjar;
            this.Ultracart = ultracart;
            this.Warning = warning;
        }
        
        /// <summary>
        /// Gets or Sets Avalara
        /// </summary>
        [DataMember(Name="avalara", EmitDefaultValue=false)]
        public TaxProviderAvalara Avalara { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name="error", EmitDefaultValue=false)]
        public Error Error { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [DataMember(Name="metadata", EmitDefaultValue=false)]
        public ResponseMetadata Metadata { get; set; }

        /// <summary>
        /// Gets or Sets Self
        /// </summary>
        [DataMember(Name="self", EmitDefaultValue=false)]
        public TaxProviderSelf Self { get; set; }

        /// <summary>
        /// Gets or Sets Sovos
        /// </summary>
        [DataMember(Name="sovos", EmitDefaultValue=false)]
        public TaxProviderSovos Sovos { get; set; }

        /// <summary>
        /// Indicates if API call was successful
        /// </summary>
        /// <value>Indicates if API call was successful</value>
        [DataMember(Name="success", EmitDefaultValue=false)]
        public bool? Success { get; set; }

        /// <summary>
        /// Gets or Sets Taxjar
        /// </summary>
        [DataMember(Name="taxjar", EmitDefaultValue=false)]
        public TaxProviderTaxJar Taxjar { get; set; }

        /// <summary>
        /// Gets or Sets Ultracart
        /// </summary>
        [DataMember(Name="ultracart", EmitDefaultValue=false)]
        public TaxProviderUltraCart Ultracart { get; set; }

        /// <summary>
        /// Gets or Sets Warning
        /// </summary>
        [DataMember(Name="warning", EmitDefaultValue=false)]
        public Warning Warning { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TaxProvidersResponse {\n");
            sb.Append("  Avalara: ").Append(Avalara).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Self: ").Append(Self).Append("\n");
            sb.Append("  Sovos: ").Append(Sovos).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Taxjar: ").Append(Taxjar).Append("\n");
            sb.Append("  Ultracart: ").Append(Ultracart).Append("\n");
            sb.Append("  Warning: ").Append(Warning).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TaxProvidersResponse);
        }

        /// <summary>
        /// Returns true if TaxProvidersResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TaxProvidersResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TaxProvidersResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Avalara == input.Avalara ||
                    (this.Avalara != null &&
                    this.Avalara.Equals(input.Avalara))
                ) && 
                (
                    this.Error == input.Error ||
                    (this.Error != null &&
                    this.Error.Equals(input.Error))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    (this.Metadata != null &&
                    this.Metadata.Equals(input.Metadata))
                ) && 
                (
                    this.Self == input.Self ||
                    (this.Self != null &&
                    this.Self.Equals(input.Self))
                ) && 
                (
                    this.Sovos == input.Sovos ||
                    (this.Sovos != null &&
                    this.Sovos.Equals(input.Sovos))
                ) && 
                (
                    this.Success == input.Success ||
                    (this.Success != null &&
                    this.Success.Equals(input.Success))
                ) && 
                (
                    this.Taxjar == input.Taxjar ||
                    (this.Taxjar != null &&
                    this.Taxjar.Equals(input.Taxjar))
                ) && 
                (
                    this.Ultracart == input.Ultracart ||
                    (this.Ultracart != null &&
                    this.Ultracart.Equals(input.Ultracart))
                ) && 
                (
                    this.Warning == input.Warning ||
                    (this.Warning != null &&
                    this.Warning.Equals(input.Warning))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Avalara != null)
                    hashCode = hashCode * 59 + this.Avalara.GetHashCode();
                if (this.Error != null)
                    hashCode = hashCode * 59 + this.Error.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.Self != null)
                    hashCode = hashCode * 59 + this.Self.GetHashCode();
                if (this.Sovos != null)
                    hashCode = hashCode * 59 + this.Sovos.GetHashCode();
                if (this.Success != null)
                    hashCode = hashCode * 59 + this.Success.GetHashCode();
                if (this.Taxjar != null)
                    hashCode = hashCode * 59 + this.Taxjar.GetHashCode();
                if (this.Ultracart != null)
                    hashCode = hashCode * 59 + this.Ultracart.GetHashCode();
                if (this.Warning != null)
                    hashCode = hashCode * 59 + this.Warning.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
