/*
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = com.ultracart.admin.v2.Client.OpenAPIDateConverter;

namespace com.ultracart.admin.v2.Model
{
    /// <summary>
    /// TimelineSummary
    /// </summary>
    [DataContract]
    public partial class TimelineSummary :  IEquatable<TimelineSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TimelineSummary" /> class.
        /// </summary>
        /// <param name="availableSeconds">Seconds the agent was Available (incl. Busy).</param>
        /// <param name="avgHandleTimeSeconds">Average handle time across calls and chats, in seconds.</param>
        /// <param name="callsMissed">Calls the agent missed (inbound, disposition&#x3D;missed).</param>
        /// <param name="callsTaken">Calls the agent took.</param>
        /// <param name="chatsHandled">Chats the agent handled.</param>
        public TimelineSummary(long availableSeconds = default(long), long avgHandleTimeSeconds = default(long), int callsMissed = default(int), int callsTaken = default(int), int chatsHandled = default(int))
        {
            this.AvailableSeconds = availableSeconds;
            this.AvgHandleTimeSeconds = avgHandleTimeSeconds;
            this.CallsMissed = callsMissed;
            this.CallsTaken = callsTaken;
            this.ChatsHandled = chatsHandled;
        }

        /// <summary>
        /// Seconds the agent was Available (incl. Busy)
        /// </summary>
        /// <value>Seconds the agent was Available (incl. Busy)</value>
        [DataMember(Name="available_seconds", EmitDefaultValue=false)]
        public long AvailableSeconds { get; set; }

        /// <summary>
        /// Average handle time across calls and chats, in seconds
        /// </summary>
        /// <value>Average handle time across calls and chats, in seconds</value>
        [DataMember(Name="avg_handle_time_seconds", EmitDefaultValue=false)]
        public long AvgHandleTimeSeconds { get; set; }

        /// <summary>
        /// Calls the agent missed (inbound, disposition&#x3D;missed)
        /// </summary>
        /// <value>Calls the agent missed (inbound, disposition&#x3D;missed)</value>
        [DataMember(Name="calls_missed", EmitDefaultValue=false)]
        public int CallsMissed { get; set; }

        /// <summary>
        /// Calls the agent took
        /// </summary>
        /// <value>Calls the agent took</value>
        [DataMember(Name="calls_taken", EmitDefaultValue=false)]
        public int CallsTaken { get; set; }

        /// <summary>
        /// Chats the agent handled
        /// </summary>
        /// <value>Chats the agent handled</value>
        [DataMember(Name="chats_handled", EmitDefaultValue=false)]
        public int ChatsHandled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TimelineSummary {\n");
            sb.Append("  AvailableSeconds: ").Append(AvailableSeconds).Append("\n");
            sb.Append("  AvgHandleTimeSeconds: ").Append(AvgHandleTimeSeconds).Append("\n");
            sb.Append("  CallsMissed: ").Append(CallsMissed).Append("\n");
            sb.Append("  CallsTaken: ").Append(CallsTaken).Append("\n");
            sb.Append("  ChatsHandled: ").Append(ChatsHandled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TimelineSummary);
        }

        /// <summary>
        /// Returns true if TimelineSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of TimelineSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TimelineSummary input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AvailableSeconds == input.AvailableSeconds ||
                    (this.AvailableSeconds != null &&
                    this.AvailableSeconds.Equals(input.AvailableSeconds))
                ) && 
                (
                    this.AvgHandleTimeSeconds == input.AvgHandleTimeSeconds ||
                    (this.AvgHandleTimeSeconds != null &&
                    this.AvgHandleTimeSeconds.Equals(input.AvgHandleTimeSeconds))
                ) && 
                (
                    this.CallsMissed == input.CallsMissed ||
                    (this.CallsMissed != null &&
                    this.CallsMissed.Equals(input.CallsMissed))
                ) && 
                (
                    this.CallsTaken == input.CallsTaken ||
                    (this.CallsTaken != null &&
                    this.CallsTaken.Equals(input.CallsTaken))
                ) && 
                (
                    this.ChatsHandled == input.ChatsHandled ||
                    (this.ChatsHandled != null &&
                    this.ChatsHandled.Equals(input.ChatsHandled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AvailableSeconds != null)
                    hashCode = hashCode * 59 + this.AvailableSeconds.GetHashCode();
                if (this.AvgHandleTimeSeconds != null)
                    hashCode = hashCode * 59 + this.AvgHandleTimeSeconds.GetHashCode();
                if (this.CallsMissed != null)
                    hashCode = hashCode * 59 + this.CallsMissed.GetHashCode();
                if (this.CallsTaken != null)
                    hashCode = hashCode * 59 + this.CallsTaken.GetHashCode();
                if (this.ChatsHandled != null)
                    hashCode = hashCode * 59 + this.ChatsHandled.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
