/* 
 * UltraCart Rest API V2
 *
 * UltraCart REST API Version 2
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@ultracart.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.ultracart.admin.v2.Api;
using com.ultracart.admin.v2.Model;
using com.ultracart.admin.v2.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.ultracart.admin.v2.Test
{
    /// <summary>
    ///  Class for testing CheckoutStateProvinceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckoutStateProvinceResponseTests
    {
        // TODO uncomment below to declare an instance variable for CheckoutStateProvinceResponse
        //private CheckoutStateProvinceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CheckoutStateProvinceResponse
            //instance = new CheckoutStateProvinceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CheckoutStateProvinceResponse
        /// </summary>
        [Test]
        public void CheckoutStateProvinceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CheckoutStateProvinceResponse
            //Assert.IsInstanceOfType<CheckoutStateProvinceResponse> (instance, "variable 'instance' is a CheckoutStateProvinceResponse");
        }


        /// <summary>
        /// Test the property 'StateProvinces'
        /// </summary>
        [Test]
        public void StateProvincesTest()
        {
            // TODO unit test for the property 'StateProvinces'
        }

    }

}
